; ============================================================================
; Novus Minimal AmigaOS Startup Code
; ============================================================================
; Provides a clean entry point for Novus programs that doesn't require
; VBCC's startup.o or -lamiga dependencies
; ============================================================================

; ============================================================================
; Stack Size Declaration
; ============================================================================
; Stack cookie is now generated per-program to support #[stack_size(N)]
; The ___stack_cookie and ___stack symbols are defined in stack_config.s
; which is generated by the compiler for each program.
; ============================================================================

; ============================================================================
; Code Section
; ============================================================================
	section	"CODE",code

; ============================================================================
; External References
; ============================================================================
	xref	_main			; User's main() function
	xref	_SysBase		; From library_bases.s
	xref	_DOSBase		; From library_bases.s
	xref	_IntuitionBase		; From library_bases.s
	xref	_GadToolsBase		; From library_bases.s
	xref	_GfxBase		; From library_bases.s
	xref	_WBStartupMsg		; From library_bases.s (WBStartup message)
	xref	___dos_init		; From dos_init.s
	xref	___dos_cleanup		; From dos_init.s
	xref	___graphics_init	; From graphics_init.s
	xref	___graphics_cleanup	; From graphics_init.s

; ============================================================================
; Entry Point
; ============================================================================
	xdef	_start			; Entry point for executable

_start:
	; AmigaOS entry point - can be called from CLI or Workbench
	; Detection strategy:
	;   CLI:       d0 = 0 (no WBStartup message on port yet)
	;   Workbench: d0 = 0, but pr_CLI field in Process is NULL
	;
	; We need to check our Process structure to determine launch type

	; Initialize SysBase from absolute location 4
	move.l	4.w,a6
	move.l	a6,_SysBase

	; Clear WBStartup message pointer (assume CLI)
	clr.l	_WBStartupMsg

	; Get our Process structure via FindTask(NULL)
	suba.l	a1,a1			; NULL parameter
	jsr	-294(a6)		; FindTask() - LVO -294
	move.l	d0,a4			; Save Process pointer in a4

	; Check pr_CLI field in Process structure
	; Process struct layout:
	;   +0:  pr_Task (76 bytes)
	;   +76: pr_MsgPort (34 bytes)
	;   +110: pr_Pad (2 bytes)
	;   +112: pr_SegList (4 bytes)
	;   +116: pr_StackSize (4 bytes)
	;   +120: pr_GlobVec (4 bytes)
	;   +124: pr_TaskNum (4 bytes)
	;   +128: pr_StackBase (4 bytes)
	;   +132: pr_Result2 (4 bytes)
	;   +136: pr_CurrentDir (4 bytes)
	;   +140: pr_CIS (4 bytes)
	;   +144: pr_COS (4 bytes)
	;   +148: pr_ConsoleTask (4 bytes)
	;   +152: pr_FileSystemTask (4 bytes)
	;   +156: pr_CLI (4 bytes) <- This is what we check
	;
	move.l	156(a4),d0		; Get pr_CLI field
	bne.s	.cli_startup		; If non-zero, we're CLI

	; Workbench startup - get WBStartup message
	; The message is at our Process's message port (pr_MsgPort at offset 76)
	lea	76(a4),a0		; a0 = &pr_MsgPort
	movea.l	_SysBase,a6		; Get exec.library base
	jsr	-384(a6)		; WaitPort() - LVO -384

	lea	76(a4),a0		; a0 = &pr_MsgPort again
	movea.l	_SysBase,a6		; Get exec.library base
	jsr	-372(a6)		; GetMsg() - LVO -372

	move.l	d0,_WBStartupMsg	; Save WBStartup message pointer
	beq.w	.exit_no_msg		; If NULL, something went wrong (use word-sized branch)

	; Set current directory to first WBArg's lock (the program icon's directory)
	; WBStartup struct layout:
	;   +0:  sm_Message (20 bytes)
	;   +20: sm_Process (4 bytes)
	;   +24: sm_Segment (4 bytes)
	;   +28: sm_NumArgs (4 bytes)
	;   +32: sm_ToolWindow (4 bytes)
	;   +36: sm_ArgList (4 bytes) <- pointer to WBArg array
	;
	move.l	d0,a2			; a2 = WBStartup message
	move.l	36(a2),a3		; a3 = ArgList pointer
	move.l	(a3),d1			; d1 = first WBArg's wa_Lock
	beq.s	.no_lock		; If lock is NULL, skip CurrentDir

	; Call CurrentDir(lock)
	movea.l	_DOSBase,a6		; Get dos.library base (need to open it first!)
	; Actually, we need to open DOS first. Let's do that below.

.no_lock:
.cli_startup:
	; Initialize DOS library (needed by runtime I/O functions)
	jsr	___dos_init
	tst.l	d0
	beq.w	.exit_no_dos		; Exit if DOS library couldn't open (use word-sized branch)

	; If Workbench startup and we have a lock, set current directory
	tst.l	_WBStartupMsg
	beq.s	.skip_currentdir	; Skip if CLI

	move.l	_WBStartupMsg,a2	; Get WBStartup message
	move.l	36(a2),a3		; Get ArgList pointer
	move.l	(a3),d1			; Get first WBArg's wa_Lock
	beq.s	.skip_currentdir	; Skip if lock is NULL

	; Call CurrentDir(lock)
	movea.l	_DOSBase,a6		; Get dos.library base
	jsr	-126(a6)		; CurrentDir() - LVO -126

.skip_currentdir:
	; Initialize Graphics library
	jsr	___graphics_init
	; Note: Don't fail if graphics.library doesn't open - not all programs need it
	; The library stubs will handle NULL base pointers gracefully

	; Open intuition.library v33
	movea.l	_SysBase,a6		; Get exec.library base
	lea	.intuition_name(pc),a1	; Library name
	moveq	#33,d0			; Minimum version (v33 = AmigaOS 1.2+)
	jsr	-552(a6)		; OpenLibrary()
	move.l	d0,_IntuitionBase	; Save the base
	beq.s	.no_intuition		; If NULL, skip cleanup

	; Open gadtools.library v37
	movea.l	_SysBase,a6		; Get exec.library base
	lea	.gadtools_name(pc),a1	; Library name
	moveq	#37,d0			; Minimum version (v37 = AmigaOS 2.0+)
	jsr	-552(a6)		; OpenLibrary()
	move.l	d0,_GadToolsBase	; Save the base
	beq.s	.no_gadtools		; If NULL, skip gadtools cleanup

	; Call main()
	jsr	_main

	; Close gadtools.library
	move.l	d0,-(sp)		; Save return code
	movea.l	_SysBase,a6		; Get exec.library base
	movea.l	_GadToolsBase,a1	; Library to close
	jsr	-414(a6)		; CloseLibrary()
	move.l	(sp)+,d0		; Restore return code

.no_gadtools:
	; Close intuition.library
	move.l	d0,-(sp)		; Save return code
	movea.l	_SysBase,a6		; Get exec.library base
	movea.l	_IntuitionBase,a1	; Library to close
	jsr	-414(a6)		; CloseLibrary()
	move.l	(sp)+,d0		; Restore return code

.no_intuition:
	; Clean up Graphics library
	move.l	d0,-(sp)		; Save return code
	jsr	___graphics_cleanup
	move.l	(sp)+,d0		; Restore return code

	; Clean up DOS library
	move.l	d0,-(sp)		; Save return code
	jsr	___dos_cleanup
	move.l	(sp)+,d0		; Restore return code

	; Reply to WBStartup message if we got one
	tst.l	_WBStartupMsg
	beq.s	.no_wb_reply		; Skip if CLI

	movea.l	_SysBase,a6		; Get exec.library base
	movea.l	_WBStartupMsg,a1	; Get WBStartup message
	jsr	-378(a6)		; ReplyMsg() - LVO -378

.no_wb_reply:
.exit_no_dos:
.exit_no_msg:
	; Exit with return code from main (already in d0)
	rts				; Return to CLI/Workbench

.intuition_name:
	dc.b	'intuition.library',0
	even

.gadtools_name:
	dc.b	'gadtools.library',0
	even

