using System.Text;
using Novus.IR;

namespace Novus.Codegen.M68k;

/// <summary>
/// Direct 68k assembly code generator for Novus.
/// Generates vasm-compatible assembly from Novus IR.
///
/// Target: Motorola 68000 family (68000, 68020, 68030, 68040, 68060)
/// Assembler: vasm (Motorola syntax)
/// Linker: vlink
/// Output: Amiga executable (HUNK format)
///
/// This is a prototype implementation focusing on:
/// - Basic arithmetic and logic operations
/// - Integer comparisons
/// - Control flow (if/else, loops)
/// - Simple function calls
/// - Stack-based local variables
///
/// Future enhancements:
/// - Register allocation with liveness analysis
/// - Peephole optimization
/// - Inline assembly support
/// - Hardware register access
/// - AmigaOS library calls
/// </summary>
public class M68kCodeGenerator
{
    private readonly IrModule _module;
    private readonly List<IrStringLiteral> _stringLiterals;
    private readonly string _cpuTarget;
    private readonly StringBuilder _output;
    private readonly StringBuilder _dataSection;
    private readonly StringBuilder _bssSection;

    public M68kCodeGenerator(IrModule module, List<IrStringLiteral> stringLiterals, string cpuTarget)
    {
        _module = module;
        _stringLiterals = stringLiterals;
        _cpuTarget = cpuTarget;
        _output = new StringBuilder();
        _dataSection = new StringBuilder();
        _bssSection = new StringBuilder();
    }

    /// <summary>
    /// Generate complete assembly file
    /// </summary>
    public string Generate()
    {
        var result = new StringBuilder();

        // File header and assembler directives
        EmitHeader(result);

        // Generate data section (constants, string literals)
        GenerateDataSection();

        // Generate BSS section (uninitialized globals)
        GenerateBssSection();

        // Generate code section (functions)
        GenerateCodeSection();

        // Combine sections
        if (_dataSection.Length > 0)
        {
            result.AppendLine();
            result.AppendLine("    SECTION data,DATA");
            result.AppendLine();
            result.Append(_dataSection);
        }

        if (_bssSection.Length > 0)
        {
            result.AppendLine();
            result.AppendLine("    SECTION bss,BSS");
            result.AppendLine();
            result.Append(_bssSection);
        }

        result.AppendLine();
        result.AppendLine("    SECTION code,CODE");
        result.AppendLine();
        result.Append(_output);

        return result.ToString();
    }

    private void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("; Novus M68k Assembly Output");
        sb.AppendLine("; Generated by Novus Compiler");
        sb.AppendLine(";");
        sb.AppendLine($"; Target CPU: {_cpuTarget}");
        sb.AppendLine(";");
        sb.AppendLine("; =============================================================================");
        sb.AppendLine("; CALLING CONVENTION (Novus Application ABI)");
        sb.AppendLine("; =============================================================================");
        sb.AppendLine(";");
        sb.AppendLine("; This is the convention for Novus APPLICATION code (internal functions).");
        sb.AppendLine("; AmigaOS library calls use A6 for library base - see note below.");
        sb.AppendLine(";");
        sb.AppendLine("; Register Usage:");
        sb.AppendLine(";   D0-D1     : Volatile (caller-saved). Return values in D0 (D1 for 64-bit)");
        sb.AppendLine(";   D2-D7     : Preserved (callee-saved). Free for local use if saved.");
        sb.AppendLine(";   A0-A1     : Volatile (caller-saved). Used for address parameters.");
        sb.AppendLine(";   A2-A4     : Preserved (callee-saved). Free for local use if saved.");
        sb.AppendLine(";   A5        : Frame Pointer (FP). Points to local stack frame.");
        sb.AppendLine(";   A6        : Preserved. Reserved for AmigaOS library base in library calls.");
        sb.AppendLine(";   A7 (SP)   : Stack Pointer. Always points to top of stack.");
        sb.AppendLine(";");
        sb.AppendLine("; Parameter Passing:");
        sb.AppendLine(";   Arguments pushed right-to-left onto stack.");
        sb.AppendLine(";   Caller cleans up stack after call returns.");
        sb.AppendLine(";");
        sb.AppendLine("; Stack Frame (created by LINK A5,#-framesize):");
        sb.AppendLine(";   [A5+8]    : First argument (if any)");
        sb.AppendLine(";   [A5+4]    : Return address");
        sb.AppendLine(";   [A5]      : Saved A5 (old frame pointer)");
        sb.AppendLine(";   [A5-4]    : First local variable");
        sb.AppendLine(";   ...       : More locals");
        sb.AppendLine(";   [SP]      : Top of stack (after LINK)");
        sb.AppendLine(";");
        sb.AppendLine("; IMPORTANT: A6 and AmigaOS Library Calls");
        sb.AppendLine("; -----------------------------------------");
        sb.AppendLine("; AmigaOS uses A6 to hold the library base pointer for all library calls.");
        sb.AppendLine("; When calling an AmigaOS function (e.g., OpenLibrary, AllocMem):");
        sb.AppendLine(";   1. Load library base into A6: move.l _SysBase,a6");
        sb.AppendLine(";   2. Call via negative offset: jsr LVO_OpenLibrary(a6)");
        sb.AppendLine(";");
        sb.AppendLine("; Novus-generated code PRESERVES A6 across function calls.");
        sb.AppendLine("; FFI wrappers save/restore A6 when transitioning to AmigaOS.");
        sb.AppendLine(";");
        sb.AppendLine("; =============================================================================");
        sb.AppendLine();

        // CPU target directive
        string cpuDirective = _cpuTarget switch
        {
            "68000" or "000" => "68000",
            "68010" or "010" => "68010",
            "68020" or "020" => "68020",
            "68030" or "030" => "68030",
            "68040" or "040" => "68040",
            "68060" or "060" => "68060",
            _ => "68020" // Default to 68020
        };

        sb.AppendLine($"    CPU {cpuDirective}");
    }

    private void GenerateDataSection()
    {
        // String literals
        if (_stringLiterals.Count > 0)
        {
            _dataSection.AppendLine("; String literals");

            foreach (var str in _stringLiterals)
            {
                _dataSection.AppendLine($"{str.Label}:");
                EmitStringData(str.Value, _dataSection);
            }

            _dataSection.AppendLine();
        }

        // Static variables with initial values
        foreach (var staticVar in _module.StaticVariables)
        {
            if (staticVar.InitialValue != null)
            {
                _dataSection.AppendLine($"; Static: {staticVar.Name}");
                _dataSection.AppendLine($"{staticVar.Name}:");
                EmitStaticInitializer(staticVar, _dataSection);
                _dataSection.AppendLine();
            }
        }
    }

    private void GenerateBssSection()
    {
        // Static variables without initial values (zero-initialized)
        foreach (var staticVar in _module.StaticVariables)
        {
            if (staticVar.InitialValue == null)
            {
                _bssSection.AppendLine($"; Static: {staticVar.Name}");
                _bssSection.AppendLine($"{staticVar.Name}:");
                _bssSection.AppendLine($"    ds.b      {staticVar.Type.SizeInBytes}");
                _bssSection.AppendLine();
            }
        }
    }

    private void GenerateCodeSection()
    {
        // Generate all functions
        foreach (var function in _module.Functions)
        {
            if (!function.IsExtern)
            {
                GenerateFunction(function);
            }
        }
    }

    private void GenerateFunction(IrFunction function)
    {
        _output.AppendLine($"; Function: {function.Name}");
        _output.AppendLine($"; Returns: {function.ReturnType.Name}");
        _output.AppendLine($"; Visibility: {function.Visibility}");

        // Export public functions
        if (function.Visibility == Visibility.Public || function.IsExported)
        {
            _output.AppendLine($"    XDEF      {function.Name}");
        }

        _output.AppendLine();
        _output.AppendLine($"{function.Name}:");

        // Allocate registers and stack space
        var allocator = new RegisterAllocator(function);
        allocator.AllocateRegisters();

        var selector = new InstructionSelector(allocator, _output, _cpuTarget);

        // Emit function prologue
        EmitPrologue(function, allocator);

        // Generate code for each basic block
        bool isFirstBlock = true;
        foreach (var block in function.BasicBlocks)
        {
            GenerateBasicBlock(block, selector, allocator, isFirstBlock);
            isFirstBlock = false;
        }

        // Emit function epilogue (if not already emitted by return)
        _output.AppendLine();
        _output.AppendLine($"{function.Name}_epilogue:");
        EmitEpilogue(function, allocator);

        _output.AppendLine();
    }

    private void EmitPrologue(IrFunction function, RegisterAllocator allocator)
    {
        _output.AppendLine("    ; Function prologue");

        int frameSize = allocator.GetStackFrameSize();

        // Create stack frame
        if (frameSize > 0)
        {
            _output.AppendLine($"    link      a5,#{-frameSize}");
        }
        else
        {
            _output.AppendLine($"    link      a5,#0");
        }

        // Save preserved registers if used
        var preservedRegs = allocator.GetPreservedRegisters().ToList();
        if (preservedRegs.Count > 0)
        {
            string regList = BuildRegisterList(preservedRegs);
            _output.AppendLine($"    movem.l   {regList},-(sp)");
        }

        _output.AppendLine();
    }

    private void EmitEpilogue(IrFunction function, RegisterAllocator allocator)
    {
        _output.AppendLine("    ; Function epilogue");

        // Restore preserved registers
        var preservedRegs = allocator.GetPreservedRegisters().ToList();
        if (preservedRegs.Count > 0)
        {
            string regList = BuildRegisterList(preservedRegs);
            _output.AppendLine($"    movem.l   (sp)+,{regList}");
        }

        // Destroy stack frame
        _output.AppendLine($"    unlk      a5");

        // Return
        _output.AppendLine($"    rts");
    }

    private void GenerateBasicBlock(IrBasicBlock block, InstructionSelector selector, RegisterAllocator allocator, bool isEntryBlock)
    {
        // Emit block label (skip for entry block - function label already emitted)
        if (!isEntryBlock)
        {
            selector.EmitLabel(block.Label);
        }

        // Generate instructions
        foreach (var instruction in block.Instructions)
        {
            GenerateInstruction(instruction, selector, allocator);
        }
    }

    private void GenerateInstruction(IrInstruction instruction, InstructionSelector selector, RegisterAllocator allocator)
    {
        switch (instruction)
        {
            case IrBinaryOp binOp:
                selector.EmitBinaryOp(binOp, binOp.ResultName);
                break;

            case IrCall call:
                selector.EmitCall(call);
                break;

            case IrReturn ret:
                selector.EmitReturn(ret);
                // Branch to epilogue
                _output.AppendLine($"    bra       {GetCurrentFunctionName()}_epilogue");
                break;

            case IrBranch branch:
                selector.EmitBranch(branch.Target);
                break;

            case IrConditionalBranch condBranch:
                selector.EmitConditionalBranch(condBranch.Condition, condBranch.TrueTarget, condBranch.FalseTarget);
                break;

            case IrLabel label:
                selector.EmitLabel(label.Name);
                break;

            case IrLocalDecl localDecl:
                // Stack space already allocated - just store initial value
                if (localDecl.InitialValue != null)
                {
                    selector.EmitLoadValue(localDecl.InitialValue, M68kRegister.D0, localDecl.Type);
                    selector.EmitStoreRegister(M68kRegister.D0, localDecl.Name, localDecl.Type);
                }
                break;

            case IrStore store:
                selector.EmitLoadValue(store.Value, M68kRegister.D0, store.Value.Type);
                selector.EmitStoreRegister(M68kRegister.D0, store.VariableName, store.Value.Type);
                break;

            default:
                _output.AppendLine($"    ; TODO: {instruction.GetType().Name}");
                break;
        }
    }

    private string GetCurrentFunctionName()
    {
        // This is a hack - in real implementation, track current function
        // For prototype, we can extract it from the output
        var lines = _output.ToString().Split('\n');
        for (int i = lines.Length - 1; i >= 0; i--)
        {
            if (lines[i].Contains("Function:"))
            {
                return lines[i].Split(':')[1].Trim();
            }
        }
        return "unknown";
    }

    private string BuildRegisterList(List<M68kRegister> registers)
    {
        // Build register list for MOVEM instruction (e.g., "d2-d7/a2-a4")
        var dataRegs = registers.Where(r => r.IsDataRegister()).OrderBy(r => (int)r).ToList();
        var addrRegs = registers.Where(r => r.IsAddressRegister()).OrderBy(r => (int)r).ToList();

        var parts = new List<string>();

        // Add data register ranges
        if (dataRegs.Count > 0)
        {
            parts.Add(BuildRegisterRange(dataRegs));
        }

        // Add address register ranges
        if (addrRegs.Count > 0)
        {
            parts.Add(BuildRegisterRange(addrRegs));
        }

        return string.Join("/", parts);
    }

    private string BuildRegisterRange(List<M68kRegister> registers)
    {
        if (registers.Count == 0) return "";
        if (registers.Count == 1) return registers[0].ToAsmString();

        // Find consecutive ranges
        var ranges = new List<string>();
        int start = 0;

        for (int i = 1; i <= registers.Count; i++)
        {
            if (i == registers.Count || (int)registers[i] != (int)registers[i - 1] + 1)
            {
                // End of range
                if (i - start == 1)
                {
                    ranges.Add(registers[start].ToAsmString());
                }
                else
                {
                    ranges.Add($"{registers[start].ToAsmString()}-{registers[i - 1].ToAsmString()}");
                }
                start = i;
            }
        }

        return string.Join("/", ranges);
    }

    private void EmitStringData(string str, StringBuilder sb)
    {
        // Emit string as DC.B with null terminator
        sb.Append("    DC.B      ");

        for (int i = 0; i < str.Length; i++)
        {
            if (i > 0) sb.Append(",");

            char c = str[i];
            if (c >= 32 && c <= 126 && c != '\'' && c != '\"')
            {
                sb.Append($"'{c}'");
            }
            else
            {
                sb.Append($"${(int)c:X2}");
            }
        }

        // Null terminator
        sb.AppendLine(",0");

        // Align to word boundary
        if ((str.Length + 1) % 2 != 0)
        {
            sb.AppendLine("    DC.B      0              ; Padding");
        }
    }

    private void EmitStaticInitializer(IrStaticVariable staticVar, StringBuilder sb)
    {
        var value = staticVar.InitialValue;

        switch (value)
        {
            case IrConstant constant:
                EmitConstantData(constant, staticVar.Type, sb);
                break;

            case IrBoolConstant boolConstant:
                sb.AppendLine($"    DC.B      {(boolConstant.Value ? 1 : 0)}");
                break;

            default:
                // Zero-initialize
                sb.AppendLine($"    DS.B      {staticVar.Type.SizeInBytes}");
                break;
        }
    }

    private void EmitConstantData(IrConstant constant, IrType type, StringBuilder sb)
    {
        string directive = type.SizeInBytes switch
        {
            1 => "DC.B",
            2 => "DC.W",
            4 => "DC.L",
            _ => "DC.B"
        };

        sb.AppendLine($"    {directive}      {constant.Value}");
    }
}
