// Generated by Novus compiler
// Target: AmigaOS 2.0+ (68020+), C99

#include <stdint.h>
#include <stdbool.h>

// String type (fat pointer: pointer + length)
typedef struct {
    uint8_t* ptr;
    int32_t len;
} String;

// Enum types
// Enum: DosError
enum DosError_Tag {
    DosError_NotFound = 0,
    DosError_AlreadyExists = 1,
    DosError_DirNotFound = 2,
    DosError_DirectoryNotEmpty = 3,
    DosError_PermissionDenied = 4,
    DosError_WriteProtected = 5,
    DosError_ReadProtected = 6,
    DosError_DeleteProtected = 7,
    DosError_DiskFull = 8,
    DosError_DiskNotValidated = 9,
    DosError_DiskWriteProtected = 10,
    DosError_NoDisk = 11,
    DosError_NotADosDisk = 12,
    DosError_DeviceNotMounted = 13,
    DosError_SeekError = 14,
    DosError_BufferOverflow = 15,
    DosError_BadStreamName = 16,
    DosError_NoFreeStore = 17,
    DosError_ObjectInUse = 18,
    DosError_ObjectTooLarge = 19,
    DosError_TooManyLevels = 20,
    DosError_InvalidLock = 21,
    DosError_RecordNotLocked = 22,
    DosError_LockCollision = 23,
    DosError_LockTimeout = 24,
    DosError_NotImplemented = 25,
    DosError_BadNumber = 26,
    DosError_InvalidInput = 27,
    DosError_Unknown = 28
};

union DosError_Data {
    char _dummy;
};

typedef struct {
    enum DosError_Tag tag;
    union DosError_Data data;
} DosError;

// Enum: Option
enum Option_ptr_u8_Tag {
    Option_ptr_u8_Some = 0,
    Option_ptr_u8_None = 1
};

union Option_ptr_u8_Data {
    struct {
        uint8_t* _0;
    } Some;
};

typedef struct {
    enum Option_ptr_u8_Tag tag;
    union Option_ptr_u8_Data data;
} Option_ptr_u8;

// Enum: Result
enum Result_i32DosError_Tag {
    Result_i32DosError_Ok = 0,
    Result_i32DosError_Err = 1
};

union Result_i32DosError_Data {
    struct {
        int32_t _0;
    } Ok;
    struct {
        DosError _0;
    } Err;
};

typedef struct {
    enum Result_i32DosError_Tag tag;
    union Result_i32DosError_Data data;
} Result_i32DosError;

// String literals
static const char _str0[] = "Hello from Novus!\n";

// DOS library initialization
extern void __dos_init(void);

// Forward declarations
int main(void);

// Function implementations
int main(void) {
    __dos_init();
    String msg = (String){ .ptr = (uint8_t*)_str0, .len = 18 };
    Result_i32DosError _t0 = WriteOut(msg);
    Result_i32DosError result = _t0;
    int32_t _t1 = result.tag;
match_check_0_0:;
    bool _t2 = _t1 == 0;
    if (_t2) goto match_arm_0_0;
    goto match_check_0_1;
match_check_0_1:;
    bool _t3 = _t1 == 1;
    if (_t3) goto match_arm_0_1;
    goto match_end_0;
match_arm_0_0:;
    {
    int32_t _t4 = result.data.Ok._0;
    int32_t bytes = _t4;
    return 42;
    }
match_arm_0_1:;
    {
    DosError _t5 = result.data.Err._0;
    DosError error = _t5;
    return 1;
    }
match_end_0:;
    return;
}

