// Generated by Novus compiler
// Target: AmigaOS 2.0+ (68020+), C99

#include <stdint.h>
#include <stdbool.h>

// String type (fat pointer: pointer + length)
typedef struct {
    uint8_t* ptr;
    int32_t len;
} String;

// Enum types
// Enum: DosError
enum DosError_Tag {
    DosError_NotFound = 0,
    DosError_AlreadyExists = 1,
    DosError_DirNotFound = 2,
    DosError_DirectoryNotEmpty = 3,
    DosError_PermissionDenied = 4,
    DosError_WriteProtected = 5,
    DosError_ReadProtected = 6,
    DosError_DeleteProtected = 7,
    DosError_DiskFull = 8,
    DosError_DiskNotValidated = 9,
    DosError_DiskWriteProtected = 10,
    DosError_NoDisk = 11,
    DosError_NotADosDisk = 12,
    DosError_DeviceNotMounted = 13,
    DosError_SeekError = 14,
    DosError_BufferOverflow = 15,
    DosError_BadStreamName = 16,
    DosError_NoFreeStore = 17,
    DosError_ObjectInUse = 18,
    DosError_ObjectTooLarge = 19,
    DosError_TooManyLevels = 20,
    DosError_InvalidLock = 21,
    DosError_RecordNotLocked = 22,
    DosError_LockCollision = 23,
    DosError_LockTimeout = 24,
    DosError_NotImplemented = 25,
    DosError_BadNumber = 26,
    DosError_InvalidInput = 27,
    DosError_Unknown = 28
};

union DosError_Data {
    char _dummy;
};

typedef struct {
    enum DosError_Tag tag;
    union DosError_Data data;
} DosError;

// Enum: ExecError
enum ExecError_Tag {
    ExecError_NoMem = 0,
    ExecError_BadSignal = 1,
    ExecError_NullReturn = 2,
    ExecError_BadTask = 3,
    ExecError_BadNode = 4,
    ExecError_BadPort = 5,
    ExecError_SignalInUse = 6,
    ExecError_TaskNotFound = 7,
    ExecError_LibraryNotFound = 8,
    ExecError_InvalidAddress = 9,
    ExecError_AlignmentError = 10
};

union ExecError_Data {
    char _dummy;
};

typedef struct {
    enum ExecError_Tag tag;
    union ExecError_Data data;
} ExecError;

// Enum: IntuitionError
enum IntuitionError_Tag {
    IntuitionError_WindowOpenFailed = 0,
    IntuitionError_ScreenOpenFailed = 1,
    IntuitionError_GadgetCreateFailed = 2,
    IntuitionError_MenuCreateFailed = 3,
    IntuitionError_InvalidWindow = 4,
    IntuitionError_InvalidScreen = 5,
    IntuitionError_NoIDCMP = 6,
    IntuitionError_BadDisplayMode = 7
};

union IntuitionError_Data {
    char _dummy;
};

typedef struct {
    enum IntuitionError_Tag tag;
    union IntuitionError_Data data;
} IntuitionError;

// Enum: GraphicsError
enum GraphicsError_Tag {
    GraphicsError_BitMapAllocFailed = 0,
    GraphicsError_RastPortInitFailed = 1,
    GraphicsError_FontOpenFailed = 2,
    GraphicsError_InvalidBitMap = 3,
    GraphicsError_InvalidRastPort = 4,
    GraphicsError_BadDisplayMode = 5,
    GraphicsError_CopperListFailed = 6
};

union GraphicsError_Data {
    char _dummy;
};

typedef struct {
    enum GraphicsError_Tag tag;
    union GraphicsError_Data data;
} GraphicsError;

// Enum: NovusError
enum NovusError_Tag {
    NovusError_Dos = 0,
    NovusError_Exec = 1,
    NovusError_Intuition = 2,
    NovusError_Graphics = 3
};

union NovusError_Data {
    struct {
        DosError _0;
    } Dos;
    struct {
        ExecError _0;
    } Exec;
    struct {
        IntuitionError _0;
    } Intuition;
    struct {
        GraphicsError _0;
    } Graphics;
};

typedef struct {
    enum NovusError_Tag tag;
    union NovusError_Data data;
} NovusError;

// External function declarations (FFI)
extern int32_t IoErr(void);

// Forward declarations
DosError dos_last_error(void);
DosError dos_error_from_code(int32_t code);
int32_t dos_error_to_code(DosError err);
int32_t exec_error_to_code(ExecError err);
int32_t intuition_error_to_code(IntuitionError err);
int32_t graphics_error_to_code(GraphicsError err);
NovusError novus_error_from_dos(DosError err);
NovusError novus_error_from_exec(ExecError err);
NovusError novus_error_from_intuition(IntuitionError err);
NovusError novus_error_from_graphics(GraphicsError err);
int32_t novus_error_to_code(NovusError err);

// Function implementations
DosError dos_last_error(void) {
    int32_t _t0 = IoErr();
    int32_t code = _t0;
    DosError _t1 = dos_error_from_code(code);
    return _t1;
}

DosError dos_error_from_code(int32_t code) {
    bool _t2 = code == 205;
    if (_t2) goto if_then_0;
    goto if_end_0;
if_then_0:;
    return (DosError){ .tag = DosError_NotFound };
if_end_0:;
    bool _t3 = code == 203;
    if (_t3) goto if_then_1;
    goto if_end_1;
if_then_1:;
    return (DosError){ .tag = DosError_AlreadyExists };
if_end_1:;
    bool _t4 = code == 204;
    if (_t4) goto if_then_2;
    goto if_end_2;
if_then_2:;
    return (DosError){ .tag = DosError_DirNotFound };
if_end_2:;
    bool _t5 = code == 216;
    if (_t5) goto if_then_3;
    goto if_end_3;
if_then_3:;
    return (DosError){ .tag = DosError_DirectoryNotEmpty };
if_end_3:;
    bool _t6 = code == 223;
    if (_t6) goto if_then_4;
    goto if_end_4;
if_then_4:;
    return (DosError){ .tag = DosError_WriteProtected };
if_end_4:;
    bool _t7 = code == 224;
    if (_t7) goto if_then_5;
    goto if_end_5;
if_then_5:;
    return (DosError){ .tag = DosError_ReadProtected };
if_end_5:;
    bool _t8 = code == 222;
    if (_t8) goto if_then_6;
    goto if_end_6;
if_then_6:;
    return (DosError){ .tag = DosError_DeleteProtected };
if_end_6:;
    bool _t9 = code == 221;
    if (_t9) goto if_then_7;
    goto if_end_7;
if_then_7:;
    return (DosError){ .tag = DosError_DiskFull };
if_end_7:;
    bool _t10 = code == 213;
    if (_t10) goto if_then_8;
    goto if_end_8;
if_then_8:;
    return (DosError){ .tag = DosError_DiskNotValidated };
if_end_8:;
    bool _t11 = code == 214;
    if (_t11) goto if_then_9;
    goto if_end_9;
if_then_9:;
    return (DosError){ .tag = DosError_DiskWriteProtected };
if_end_9:;
    bool _t12 = code == 226;
    if (_t12) goto if_then_10;
    goto if_end_10;
if_then_10:;
    return (DosError){ .tag = DosError_NoDisk };
if_end_10:;
    bool _t13 = code == 225;
    if (_t13) goto if_then_11;
    goto if_end_11;
if_then_11:;
    return (DosError){ .tag = DosError_NotADosDisk };
if_end_11:;
    bool _t14 = code == 218;
    if (_t14) goto if_then_12;
    goto if_end_12;
if_then_12:;
    return (DosError){ .tag = DosError_DeviceNotMounted };
if_end_12:;
    bool _t15 = code == 219;
    if (_t15) goto if_then_13;
    goto if_end_13;
if_then_13:;
    return (DosError){ .tag = DosError_SeekError };
if_end_13:;
    bool _t16 = code == 303;
    if (_t16) goto if_then_14;
    goto if_end_14;
if_then_14:;
    return (DosError){ .tag = DosError_BufferOverflow };
if_end_14:;
    bool _t17 = code == 206;
    if (_t17) goto if_then_15;
    goto if_end_15;
if_then_15:;
    return (DosError){ .tag = DosError_BadStreamName };
if_end_15:;
    bool _t18 = code == 103;
    if (_t18) goto if_then_16;
    goto if_end_16;
if_then_16:;
    return (DosError){ .tag = DosError_NoFreeStore };
if_end_16:;
    bool _t19 = code == 202;
    if (_t19) goto if_then_17;
    goto if_end_17;
if_then_17:;
    return (DosError){ .tag = DosError_ObjectInUse };
if_end_17:;
    bool _t20 = code == 207;
    if (_t20) goto if_then_18;
    goto if_end_18;
if_then_18:;
    return (DosError){ .tag = DosError_ObjectTooLarge };
if_end_18:;
    bool _t21 = code == 217;
    if (_t21) goto if_then_19;
    goto if_end_19;
if_then_19:;
    return (DosError){ .tag = DosError_TooManyLevels };
if_end_19:;
    bool _t22 = code == 211;
    if (_t22) goto if_then_20;
    goto if_end_20;
if_then_20:;
    return (DosError){ .tag = DosError_InvalidLock };
if_end_20:;
    bool _t23 = code == 240;
    if (_t23) goto if_then_21;
    goto if_end_21;
if_then_21:;
    return (DosError){ .tag = DosError_RecordNotLocked };
if_end_21:;
    bool _t24 = code == 241;
    if (_t24) goto if_then_22;
    goto if_end_22;
if_then_22:;
    return (DosError){ .tag = DosError_LockCollision };
if_end_22:;
    bool _t25 = code == 242;
    if (_t25) goto if_then_23;
    goto if_end_23;
if_then_23:;
    return (DosError){ .tag = DosError_LockTimeout };
if_end_23:;
    bool _t26 = code == 236;
    if (_t26) goto if_then_24;
    goto if_end_24;
if_then_24:;
    return (DosError){ .tag = DosError_NotImplemented };
if_end_24:;
    bool _t27 = code == 115;
    if (_t27) goto if_then_25;
    goto if_end_25;
if_then_25:;
    return (DosError){ .tag = DosError_BadNumber };
if_end_25:;
    return (DosError){ .tag = DosError_Unknown };
}

int32_t dos_error_to_code(DosError err) {
    int32_t _t28 = err.tag;
match_check_26_0:;
    bool _t29 = _t28 == 0;
    if (_t29) goto match_arm_26_0;
    goto match_check_26_1;
match_check_26_1:;
    bool _t30 = _t28 == 1;
    if (_t30) goto match_arm_26_1;
    goto match_check_26_2;
match_check_26_2:;
    bool _t31 = _t28 == 2;
    if (_t31) goto match_arm_26_2;
    goto match_check_26_3;
match_check_26_3:;
    bool _t32 = _t28 == 3;
    if (_t32) goto match_arm_26_3;
    goto match_check_26_4;
match_check_26_4:;
    bool _t33 = _t28 == 4;
    if (_t33) goto match_arm_26_4;
    goto match_check_26_5;
match_check_26_5:;
    bool _t34 = _t28 == 5;
    if (_t34) goto match_arm_26_5;
    goto match_check_26_6;
match_check_26_6:;
    bool _t35 = _t28 == 6;
    if (_t35) goto match_arm_26_6;
    goto match_check_26_7;
match_check_26_7:;
    bool _t36 = _t28 == 7;
    if (_t36) goto match_arm_26_7;
    goto match_check_26_8;
match_check_26_8:;
    bool _t37 = _t28 == 8;
    if (_t37) goto match_arm_26_8;
    goto match_check_26_9;
match_check_26_9:;
    bool _t38 = _t28 == 9;
    if (_t38) goto match_arm_26_9;
    goto match_check_26_10;
match_check_26_10:;
    bool _t39 = _t28 == 10;
    if (_t39) goto match_arm_26_10;
    goto match_check_26_11;
match_check_26_11:;
    bool _t40 = _t28 == 11;
    if (_t40) goto match_arm_26_11;
    goto match_check_26_12;
match_check_26_12:;
    bool _t41 = _t28 == 12;
    if (_t41) goto match_arm_26_12;
    goto match_check_26_13;
match_check_26_13:;
    bool _t42 = _t28 == 13;
    if (_t42) goto match_arm_26_13;
    goto match_check_26_14;
match_check_26_14:;
    bool _t43 = _t28 == 14;
    if (_t43) goto match_arm_26_14;
    goto match_check_26_15;
match_check_26_15:;
    bool _t44 = _t28 == 15;
    if (_t44) goto match_arm_26_15;
    goto match_check_26_16;
match_check_26_16:;
    bool _t45 = _t28 == 16;
    if (_t45) goto match_arm_26_16;
    goto match_check_26_17;
match_check_26_17:;
    bool _t46 = _t28 == 17;
    if (_t46) goto match_arm_26_17;
    goto match_check_26_18;
match_check_26_18:;
    bool _t47 = _t28 == 18;
    if (_t47) goto match_arm_26_18;
    goto match_check_26_19;
match_check_26_19:;
    bool _t48 = _t28 == 19;
    if (_t48) goto match_arm_26_19;
    goto match_check_26_20;
match_check_26_20:;
    bool _t49 = _t28 == 20;
    if (_t49) goto match_arm_26_20;
    goto match_check_26_21;
match_check_26_21:;
    bool _t50 = _t28 == 21;
    if (_t50) goto match_arm_26_21;
    goto match_check_26_22;
match_check_26_22:;
    bool _t51 = _t28 == 22;
    if (_t51) goto match_arm_26_22;
    goto match_check_26_23;
match_check_26_23:;
    bool _t52 = _t28 == 23;
    if (_t52) goto match_arm_26_23;
    goto match_check_26_24;
match_check_26_24:;
    bool _t53 = _t28 == 24;
    if (_t53) goto match_arm_26_24;
    goto match_check_26_25;
match_check_26_25:;
    bool _t54 = _t28 == 25;
    if (_t54) goto match_arm_26_25;
    goto match_check_26_26;
match_check_26_26:;
    bool _t55 = _t28 == 26;
    if (_t55) goto match_arm_26_26;
    goto match_check_26_27;
match_check_26_27:;
    bool _t56 = _t28 == 27;
    if (_t56) goto match_arm_26_27;
    goto match_check_26_28;
match_check_26_28:;
    bool _t57 = _t28 == 28;
    if (_t57) goto match_arm_26_28;
    goto match_end_26;
match_arm_26_0:;
    {
    goto match_end_26;
    }
match_arm_26_1:;
    {
    goto match_end_26;
    }
match_arm_26_2:;
    {
    goto match_end_26;
    }
match_arm_26_3:;
    {
    goto match_end_26;
    }
match_arm_26_4:;
    {
    goto match_end_26;
    }
match_arm_26_5:;
    {
    goto match_end_26;
    }
match_arm_26_6:;
    {
    goto match_end_26;
    }
match_arm_26_7:;
    {
    goto match_end_26;
    }
match_arm_26_8:;
    {
    goto match_end_26;
    }
match_arm_26_9:;
    {
    goto match_end_26;
    }
match_arm_26_10:;
    {
    goto match_end_26;
    }
match_arm_26_11:;
    {
    goto match_end_26;
    }
match_arm_26_12:;
    {
    goto match_end_26;
    }
match_arm_26_13:;
    {
    goto match_end_26;
    }
match_arm_26_14:;
    {
    goto match_end_26;
    }
match_arm_26_15:;
    {
    goto match_end_26;
    }
match_arm_26_16:;
    {
    goto match_end_26;
    }
match_arm_26_17:;
    {
    goto match_end_26;
    }
match_arm_26_18:;
    {
    goto match_end_26;
    }
match_arm_26_19:;
    {
    goto match_end_26;
    }
match_arm_26_20:;
    {
    goto match_end_26;
    }
match_arm_26_21:;
    {
    goto match_end_26;
    }
match_arm_26_22:;
    {
    goto match_end_26;
    }
match_arm_26_23:;
    {
    goto match_end_26;
    }
match_arm_26_24:;
    {
    goto match_end_26;
    }
match_arm_26_25:;
    {
    goto match_end_26;
    }
match_arm_26_26:;
    {
    goto match_end_26;
    }
match_arm_26_27:;
    {
    goto match_end_26;
    }
match_arm_26_28:;
    {
    goto match_end_26;
    }
match_end_26:;
    return;
}

int32_t exec_error_to_code(ExecError err) {
    int32_t _t58 = err.tag;
match_check_27_0:;
    bool _t59 = _t58 == 0;
    if (_t59) goto match_arm_27_0;
    goto match_check_27_1;
match_check_27_1:;
    bool _t60 = _t58 == 1;
    if (_t60) goto match_arm_27_1;
    goto match_check_27_2;
match_check_27_2:;
    bool _t61 = _t58 == 2;
    if (_t61) goto match_arm_27_2;
    goto match_check_27_3;
match_check_27_3:;
    bool _t62 = _t58 == 3;
    if (_t62) goto match_arm_27_3;
    goto match_check_27_4;
match_check_27_4:;
    bool _t63 = _t58 == 4;
    if (_t63) goto match_arm_27_4;
    goto match_check_27_5;
match_check_27_5:;
    bool _t64 = _t58 == 5;
    if (_t64) goto match_arm_27_5;
    goto match_check_27_6;
match_check_27_6:;
    bool _t65 = _t58 == 6;
    if (_t65) goto match_arm_27_6;
    goto match_check_27_7;
match_check_27_7:;
    bool _t66 = _t58 == 7;
    if (_t66) goto match_arm_27_7;
    goto match_check_27_8;
match_check_27_8:;
    bool _t67 = _t58 == 8;
    if (_t67) goto match_arm_27_8;
    goto match_check_27_9;
match_check_27_9:;
    bool _t68 = _t58 == 9;
    if (_t68) goto match_arm_27_9;
    goto match_check_27_10;
match_check_27_10:;
    bool _t69 = _t58 == 10;
    if (_t69) goto match_arm_27_10;
    goto match_end_27;
match_arm_27_0:;
    {
    goto match_end_27;
    }
match_arm_27_1:;
    {
    goto match_end_27;
    }
match_arm_27_2:;
    {
    goto match_end_27;
    }
match_arm_27_3:;
    {
    goto match_end_27;
    }
match_arm_27_4:;
    {
    goto match_end_27;
    }
match_arm_27_5:;
    {
    goto match_end_27;
    }
match_arm_27_6:;
    {
    goto match_end_27;
    }
match_arm_27_7:;
    {
    goto match_end_27;
    }
match_arm_27_8:;
    {
    goto match_end_27;
    }
match_arm_27_9:;
    {
    goto match_end_27;
    }
match_arm_27_10:;
    {
    goto match_end_27;
    }
match_end_27:;
    return;
}

int32_t intuition_error_to_code(IntuitionError err) {
    int32_t _t70 = err.tag;
match_check_28_0:;
    bool _t71 = _t70 == 0;
    if (_t71) goto match_arm_28_0;
    goto match_check_28_1;
match_check_28_1:;
    bool _t72 = _t70 == 1;
    if (_t72) goto match_arm_28_1;
    goto match_check_28_2;
match_check_28_2:;
    bool _t73 = _t70 == 2;
    if (_t73) goto match_arm_28_2;
    goto match_check_28_3;
match_check_28_3:;
    bool _t74 = _t70 == 3;
    if (_t74) goto match_arm_28_3;
    goto match_check_28_4;
match_check_28_4:;
    bool _t75 = _t70 == 4;
    if (_t75) goto match_arm_28_4;
    goto match_check_28_5;
match_check_28_5:;
    bool _t76 = _t70 == 5;
    if (_t76) goto match_arm_28_5;
    goto match_check_28_6;
match_check_28_6:;
    bool _t77 = _t70 == 6;
    if (_t77) goto match_arm_28_6;
    goto match_check_28_7;
match_check_28_7:;
    bool _t78 = _t70 == 7;
    if (_t78) goto match_arm_28_7;
    goto match_end_28;
match_arm_28_0:;
    {
    goto match_end_28;
    }
match_arm_28_1:;
    {
    goto match_end_28;
    }
match_arm_28_2:;
    {
    goto match_end_28;
    }
match_arm_28_3:;
    {
    goto match_end_28;
    }
match_arm_28_4:;
    {
    goto match_end_28;
    }
match_arm_28_5:;
    {
    goto match_end_28;
    }
match_arm_28_6:;
    {
    goto match_end_28;
    }
match_arm_28_7:;
    {
    goto match_end_28;
    }
match_end_28:;
    return;
}

int32_t graphics_error_to_code(GraphicsError err) {
    int32_t _t79 = err.tag;
match_check_29_0:;
    bool _t80 = _t79 == 0;
    if (_t80) goto match_arm_29_0;
    goto match_check_29_1;
match_check_29_1:;
    bool _t81 = _t79 == 1;
    if (_t81) goto match_arm_29_1;
    goto match_check_29_2;
match_check_29_2:;
    bool _t82 = _t79 == 2;
    if (_t82) goto match_arm_29_2;
    goto match_check_29_3;
match_check_29_3:;
    bool _t83 = _t79 == 3;
    if (_t83) goto match_arm_29_3;
    goto match_check_29_4;
match_check_29_4:;
    bool _t84 = _t79 == 4;
    if (_t84) goto match_arm_29_4;
    goto match_check_29_5;
match_check_29_5:;
    bool _t85 = _t79 == 5;
    if (_t85) goto match_arm_29_5;
    goto match_check_29_6;
match_check_29_6:;
    bool _t86 = _t79 == 6;
    if (_t86) goto match_arm_29_6;
    goto match_end_29;
match_arm_29_0:;
    {
    goto match_end_29;
    }
match_arm_29_1:;
    {
    goto match_end_29;
    }
match_arm_29_2:;
    {
    goto match_end_29;
    }
match_arm_29_3:;
    {
    goto match_end_29;
    }
match_arm_29_4:;
    {
    goto match_end_29;
    }
match_arm_29_5:;
    {
    goto match_end_29;
    }
match_arm_29_6:;
    {
    goto match_end_29;
    }
match_end_29:;
    return;
}

NovusError novus_error_from_dos(DosError err) {
    return (NovusError){ .tag = NovusError_Dos, .data = { .Dos = { ._0 = err } } };
}

NovusError novus_error_from_exec(ExecError err) {
    return (NovusError){ .tag = NovusError_Exec, .data = { .Exec = { ._0 = err } } };
}

NovusError novus_error_from_intuition(IntuitionError err) {
    return (NovusError){ .tag = NovusError_Intuition, .data = { .Intuition = { ._0 = err } } };
}

NovusError novus_error_from_graphics(GraphicsError err) {
    return (NovusError){ .tag = NovusError_Graphics, .data = { .Graphics = { ._0 = err } } };
}

int32_t novus_error_to_code(NovusError err) {
    int32_t _t87 = err.tag;
match_check_30_0:;
    bool _t88 = _t87 == 0;
    if (_t88) goto match_arm_30_0;
    goto match_check_30_1;
match_check_30_1:;
    bool _t89 = _t87 == 1;
    if (_t89) goto match_arm_30_1;
    goto match_check_30_2;
match_check_30_2:;
    bool _t90 = _t87 == 2;
    if (_t90) goto match_arm_30_2;
    goto match_check_30_3;
match_check_30_3:;
    bool _t91 = _t87 == 3;
    if (_t91) goto match_arm_30_3;
    goto match_end_30;
match_arm_30_0:;
    {
    DosError _t92 = err.data.Dos._0;
    DosError dos_err = _t92;
    int32_t _t93 = dos_error_to_code(dos_err);
    goto match_end_30;
    }
match_arm_30_1:;
    {
    ExecError _t94 = err.data.Exec._0;
    ExecError exec_err = _t94;
    int32_t _t95 = exec_error_to_code(exec_err);
    goto match_end_30;
    }
match_arm_30_2:;
    {
    IntuitionError _t96 = err.data.Intuition._0;
    IntuitionError intui_err = _t96;
    int32_t _t97 = intuition_error_to_code(intui_err);
    goto match_end_30;
    }
match_arm_30_3:;
    {
    GraphicsError _t98 = err.data.Graphics._0;
    GraphicsError gfx_err = _t98;
    int32_t _t99 = graphics_error_to_code(gfx_err);
    goto match_end_30;
    }
match_end_30:;
    return;
}

