// Generated by Novus compiler
// Target: AmigaOS 2.0+ (68020+), C99

#include <stdint.h>
#include <stdbool.h>

// String type (fat pointer: pointer + length)
typedef struct {
    uint8_t* ptr;
    int32_t len;
} String;

// Enum types
// Enum: DosError
enum DosError_Tag {
    DosError_NotFound = 0,
    DosError_AlreadyExists = 1,
    DosError_DirNotFound = 2,
    DosError_DirectoryNotEmpty = 3,
    DosError_PermissionDenied = 4,
    DosError_WriteProtected = 5,
    DosError_ReadProtected = 6,
    DosError_DeleteProtected = 7,
    DosError_DiskFull = 8,
    DosError_DiskNotValidated = 9,
    DosError_DiskWriteProtected = 10,
    DosError_NoDisk = 11,
    DosError_NotADosDisk = 12,
    DosError_DeviceNotMounted = 13,
    DosError_SeekError = 14,
    DosError_BufferOverflow = 15,
    DosError_BadStreamName = 16,
    DosError_NoFreeStore = 17,
    DosError_ObjectInUse = 18,
    DosError_ObjectTooLarge = 19,
    DosError_TooManyLevels = 20,
    DosError_InvalidLock = 21,
    DosError_RecordNotLocked = 22,
    DosError_LockCollision = 23,
    DosError_LockTimeout = 24,
    DosError_NotImplemented = 25,
    DosError_BadNumber = 26,
    DosError_InvalidInput = 27,
    DosError_Unknown = 28
};

union DosError_Data {
    char _dummy;
};

typedef struct {
    enum DosError_Tag tag;
    union DosError_Data data;
} DosError;

// Enum: Result
enum Result_i32DosError_Tag {
    Result_i32DosError_Ok = 0,
    Result_i32DosError_Err = 1
};

union Result_i32DosError_Data {
    struct {
        int32_t _0;
    } Ok;
    struct {
        DosError _0;
    } Err;
};

typedef struct {
    enum Result_i32DosError_Tag tag;
    union Result_i32DosError_Data data;
} Result_i32DosError;

// External function declarations (FFI)
extern int32_t Write(int32_t file, int32_t buffer, int32_t length);
extern int32_t Output(void);

// Forward declarations
Result_i32DosError WriteOut(String message);

// Function implementations
Result_i32DosError WriteOut(String message) {
    int32_t _t0 = Output();
    int32_t stdout = _t0;
    bool _t1 = stdout == 0;
    if (_t1) goto if_then_0;
    goto if_end_0;
if_then_0:;
    return (Result_i32DosError){ .tag = Result_i32DosError_Err, .data = { .Err = { ._0 = (DosError){ .tag = DosError_InvalidInput } } } };
if_end_0:;
    uint8_t* _t2 = message.ptr;
    int32_t _t3 = message.len;
    int32_t _t4 = Write((int32_t)stdout, (int32_t)_t2, (int32_t)_t3);
    int32_t bytes = _t4;
    bool _t5 = bytes >= 0;
    if (_t5) goto if_then_1;
    goto if_end_1;
if_then_1:;
    return (Result_i32DosError){ .tag = Result_i32DosError_Ok, .data = { .Ok = { ._0 = bytes } } };
if_end_1:;
    DosError _t6 = dos_last_error();
    DosError err = _t6;
    return (Result_i32DosError){ .tag = Result_i32DosError_Err, .data = { .Err = { ._0 = err } } };
}

