<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <VSTestTestCaseFilter Condition="'$(VSTestTestCaseFilter)' == ''">Category!=CompilerIntegration&amp;Category!=CorpusCompilation&amp;Category!=FullCompilation</VSTestTestCaseFilter>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
        <PackageReference Include="Tomlyn" Version="0.17.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Novus.Core\Novus.Core.csproj" />
        <ProjectReference Include="..\Novus\Novus.csproj" />
        <ProjectReference Include="..\Novus.LanguageServer\Novus.LanguageServer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Examples\**\*.novus" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
