	; Generated by Novus compiler
	; Target: Motorola AUTO

	; External VBCC soft-float library functions
	xref	__ieeeaddl
	xref	__ieeesubl
	xref	__ieeemull
	xref	__ieeedivl
	xref	__ieeeaddd
	xref	__ieeesubd
	xref	__ieeemuld
	xref	__ieeedivd

	; External VBCC integer math library functions
	xref	__divu

	section	text,code

	; C++ constructor/destructor lists (main module only)
	section	data,data
	xdef	___CTOR_LIST__
	xdef	___DTOR_LIST__
___CTOR_LIST__:
	dc.l	0	; Count of constructors
	dc.l	0	; Terminator
___DTOR_LIST__:
	dc.l	0	; Count of destructors
	dc.l	0	; Terminator

	section	text,code

	; C library exit function (for main return)
	xref	_exit

	; CPU Detection and Initialization
	; Exported for use by external assembly code

	section	data,data

	xdef	__detected_cpu
__detected_cpu:
	dc.l	0	; 0=68000, 1=68020+, 2=68060

	; system.novus global variables (CPU, FPU, Chipset)
	xdef	_system_CPU
_system_CPU:
	dc.l	0	; SystemCPU enum value

	xdef	_system_FPU
_system_FPU:
	dc.l	0	; SystemFPU enum value

	xdef	_system_Chipset
_system_Chipset:
	dc.l	0	; SystemChipset enum value

__cpu_initialized:
	dc.l	0

	section	text,code

	; CPU detection routine - uses Amiga ExecBase AttnFlags
	; Callable from external assembly: bsr __detect_cpu
	; Result available in __detected_cpu (0=68000, 1=68020+, 2=68060)
	xdef	__detect_cpu
__detect_cpu:
	; Check if already initialized
	tst.l	__cpu_initialized
	bne	.done

	; Mark as initialized
	move.l	#1,__cpu_initialized

	; Get ExecBase (at absolute address 4)
	movea.l	4.w,a0

	; Read AttnFlags from ExecBase+296
	move.w	296(a0),d0
	move.w	d0,d1	; Save for FPU detection

	; Check for CPU flags:
	; Bit 0 ($01) = AFB_68010
	; Bit 1 ($02) = AFB_68020
	; Bit 2 ($04) = AFB_68030
	; Bit 3 ($08) = AFB_68040
	; Bit 7 ($80) = AFB_68060

	; Check for 68060
	btst	#7,d0
	beq.s	.not_68060
	move.l	#2,__detected_cpu	; 68060 detected
	move.l	#5,_system_CPU	; SystemCPU::M68060
	bra	.check_fpu

.not_68060:
	; Check for 68040
	btst	#3,d0
	beq.s	.not_68040
	move.l	#1,__detected_cpu	; 68020+ detected
	move.l	#4,_system_CPU	; SystemCPU::M68040
	bra	.check_fpu

.not_68040:
	; Check for 68030
	btst	#2,d0
	beq.s	.not_68030
	move.l	#1,__detected_cpu	; 68020+ detected
	move.l	#3,_system_CPU	; SystemCPU::M68030
	bra	.check_fpu

.not_68030:
	; Check for 68020
	btst	#1,d0
	beq.s	.not_68020
	move.l	#1,__detected_cpu	; 68020+ detected
	move.l	#2,_system_CPU	; SystemCPU::M68020
	bra	.check_fpu

.not_68020:
	; Check for 68010
	btst	#0,d0
	beq.s	.is_68000
	move.l	#0,__detected_cpu	; 68000 category
	move.l	#1,_system_CPU	; SystemCPU::M68010
	bra	.check_fpu

.is_68000:
	; Default to 68000
	move.l	#0,__detected_cpu
	move.l	#0,_system_CPU	; SystemCPU::M68000

.check_fpu:
	; Check for FPU flags (d1 has AttnFlags):
	; Bit 4 ($10) = AFB_68881
	; Bit 5 ($20) = AFB_68882
	; Bit 6 ($40) = AFB_FPU40 (68040/68060 FPU)

	; Check for 68060 FPU
	move.l	_system_CPU,d2
	cmpi.l	#5,d2	; M68060?
	bne.s	.not_68060_fpu
	btst	#6,d1	; AFB_FPU40?
	beq	.no_fpu
	move.l	#4,_system_FPU	; SystemFPU::M68060
	bra	.done

.not_68060_fpu:
	; Check for 68040 FPU
	cmpi.l	#4,d2	; M68040?
	bne.s	.not_68040_fpu
	btst	#6,d1	; AFB_FPU40?
	beq	.no_fpu
	move.l	#3,_system_FPU	; SystemFPU::M68040
	bra	.done

.not_68040_fpu:
	; Check for 68882
	btst	#5,d1
	beq.s	.not_68882
	move.l	#2,_system_FPU	; SystemFPU::M68882
	bra	.done

.not_68882:
	; Check for 68881
	btst	#4,d1
	beq	.no_fpu
	move.l	#1,_system_FPU	; SystemFPU::M68881
	bra	.done

.no_fpu:
	; No FPU (already 0 = SystemFPU::None)

.done:
	; Chipset detection would go here (requires GfxBase)
	; For now, default to OCS (0)
	rts

	; CPU dispatch stubs for optimized functions

	; Dispatch stub for main
	xdef	_main
_main:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d0
	cmpi.l	#2,d0
	beq.s	.use_68060_main
	cmpi.l	#1,d0
	beq.s	.use_68020_main

	jmp	_main_68000

.use_68020_main:
	jmp	_main_68020

.use_68060_main:
	jmp	_main_68060

	; ========================================
	; Optimized Runtime Library for Assembly
	; ========================================
	; These functions are exported for use by assembly code
	; They automatically dispatch to the optimal CPU version
	; 
	; Available functions:
	;   __mul_i32(d0, d1) -> d0    : Signed 32-bit multiply
	;   __mul_u32(d0, d1) -> d0    : Unsigned 32-bit multiply
	;   __div_u32(d0, d1) -> d0    : Unsigned 32-bit divide
	;   __shl_i32(d0, d1) -> d0    : Shift left
	;   __shr_i32(d0, d1) -> d0    : Signed shift right
	;   __shr_u32(d0, d1) -> d0    : Unsigned shift right
	; 
	; Convention: d0=operand1, d1=operand2/count, result=d0
	; All registers except d0 are preserved

	; Signed 32-bit multiply
	xdef	__mul_i32
__mul_i32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__mul_i32_68060
	cmpi.l	#1,d2
	beq.s	__mul_i32_68020
	bra.s	__mul_i32_68000

__mul_i32_68000:
	; 68000: 32-bit signed multiply using 16x16
	movem.l	d2-d4,-(sp)
	moveq	#0,d4
	tst.l	d0
	bpl.s	.pos_d0
	neg.l	d0
	not.l	d4
.pos_d0:
	tst.l	d1
	bpl.s	.pos_d1
	neg.l	d1
	not.l	d4
.pos_d1:
	move.l	d0,d2
	move.l	d1,d3
	mulu.w	d1,d0
	move.l	d2,d1
	swap	d1
	mulu.w	d3,d1
	swap	d3
	mulu.w	d3,d2
	add.l	d2,d1
	swap	d1
	clr.w	d1
	add.l	d1,d0
	tst.l	d4
	beq.s	.done
	neg.l	d0
.done:
	movem.l	(sp)+,d2-d4
	rts

__mul_i32_68020:
	; 68020: Native 32-bit multiply
	muls.l	d1,d0
	rts

__mul_i32_68060:
	; 68060: Check if constant, optimize if possible
	; For now, fall back to 68020 version
	; TODO: Optimize for known small constants
	muls.l	d1,d0
	rts

	; Unsigned 32-bit multiply
	xdef	__mul_u32
__mul_u32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__mul_u32_68060
	cmpi.l	#1,d2
	beq.s	__mul_u32_68020
	bra.s	__mul_u32_68000

__mul_u32_68000:
	; 68000: 32-bit unsigned multiply using 16x16
	movem.l	d2-d3,-(sp)
	move.l	d0,d2
	move.l	d1,d3
	mulu.w	d1,d0
	move.l	d2,d1
	swap	d1
	mulu.w	d3,d1
	swap	d3
	mulu.w	d3,d2
	add.l	d2,d1
	swap	d1
	clr.w	d1
	add.l	d1,d0
	movem.l	(sp)+,d2-d3
	rts

__mul_u32_68020:
	; 68020: Native 32-bit multiply
	mulu.l	d1,d0
	rts

__mul_u32_68060:
	; 68060: Use native multiply (runtime constants can't be optimized)
	mulu.l	d1,d0
	rts

	; Unsigned 32-bit divide
	xdef	__div_u32
__div_u32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__div_u32_68060
	cmpi.l	#1,d2
	beq.s	__div_u32_68020
	bra.s	__div_u32_68000

__div_u32_68000:
	; 68000: Call VBCC's 32-bit unsigned divide library function
	; Convention: d0=dividend, d1=divisor, result=d0, preserves d2-d7/a2-a6
	movem.l	d2/a6,-(sp)	; Save registers (VBCC requirement)
	jsr	__divu		; Call VBCC's 32/32 unsigned divide
	movem.l	(sp)+,d2/a6	; Restore registers
	rts

__div_u32_68020:
	; 68020: Native 32-bit divide
	divu.l	d1,d0
	rts

__div_u32_68060:
	; 68060: Very slow divide (>70 cycles)
	; Consider alternatives if possible
	divu.l	d1,d0
	rts

	; Shift left
	xdef	__shl_i32
__shl_i32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__shl_i32_68060
	cmpi.l	#1,d2
	beq.s	__shl_i32_68020
	bra.s	__shl_i32_68000

__shl_i32_68000:
	; 68000: Shift left (max 8 bits immediate)
	cmpi.l	#8,d1
	ble.s	.small
	lsl.l	d1,d0	; Use register shift for >8
	rts
.small:
	lsl.l	d1,d0	; Use immediate shift
	rts

__shl_i32_68020:
	; 68020: Barrel shifter handles any count
	lsl.l	d1,d0
	rts

__shl_i32_68060:
	; 68060: Barrel shifter (dual-issue friendly)
	lsl.l	d1,d0
	rts

	; Signed shift right
	xdef	__shr_i32
__shr_i32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__shr_i32_68060
	cmpi.l	#1,d2
	beq.s	__shr_i32_68020
	bra.s	__shr_i32_68000

__shr_i32_68000:
	; 68000: Signed shift right
	asr.l	d1,d0
	rts

__shr_i32_68020:
	; 68020: Barrel shifter
	asr.l	d1,d0
	rts

__shr_i32_68060:
	; 68060: Barrel shifter
	asr.l	d1,d0
	rts

	; Unsigned shift right
	xdef	__shr_u32
__shr_u32:
	; CPU already detected at startup, just read the flag
	move.l	__detected_cpu,d2
	cmpi.l	#2,d2
	beq.s	__shr_u32_68060
	cmpi.l	#1,d2
	beq.s	__shr_u32_68020
	bra.s	__shr_u32_68000

__shr_u32_68000:
	; 68000: Unsigned shift right
	lsr.l	d1,d0
	rts

__shr_u32_68020:
	; 68020: Barrel shifter
	lsr.l	d1,d0
	rts

__shr_u32_68060:
	; 68060: Barrel shifter
	lsr.l	d1,d0
	rts

	; Function: main_68000
_main_68000:
	link	a6,#-28
	; var x: i32
	moveq	#5,d0
	move.l	d0,-4(a6)
	; %t0 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; %t1 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; var a: i32
	moveq	#100,d0
	move.l	d0,-8(a6)
	; %t2 = add
	move.l	-8(a6),d0
	moveq	#50,d1
	add.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; %t3 = sub
	move.l	-8(a6),d0
	moveq	#30,d1
	sub.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; %t4 = mul
	move.l	-8(a6),d0
	moveq	#2,d1
	; 68000: Call CPU-optimized runtime primitive
	jsr	__mul_i32
	; Store to a
	move.l	d0,-8(a6)
	; %t5 = div
	move.l	-8(a6),d0
	moveq	#3,d1
	; 68000: 32-bit divide requires runtime routine
	; TODO: Call __divsi3 / __udivsi3
	divs.w	d1,d0
	; WARNING: 32-bit divide on 68000 is incomplete
	; Store to a
	move.l	d0,-8(a6)
	; Store to a
	move.l	d0,-8(a6)
	; var b: u32
	move.l	#255,d0
	move.l	d0,-12(a6)
	; %t7 = and
	move.l	-12(a6),d0
	moveq	#15,d1
	and.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; %t8 = or
	move.l	-12(a6),d0
	move.l	#240,d1
	or.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; %t9 = xor
	move.l	-12(a6),d0
	move.l	#170,d1
	eor.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; var c: u32
	moveq	#1,d0
	move.l	d0,-16(a6)
	; %t10 = shl
	move.l	-16(a6),d0
	lsl.l	#4,d0
	; Store to c
	move.l	d0,-16(a6)
	; %t11 = shr
	move.l	-16(a6),d0
	lsr.l	#2,d0
	; Store to c
	move.l	d0,-16(a6)
	; var z: i32
	moveq	#20,d0
	move.l	d0,-20(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_0_68000
	bra	if_end_0_68000
if_then_0_68000:
	; %t12 = sub
	move.l	-20(a6),d0
	moveq	#1,d1
	sub.l	d1,d0
	; Store to z
	move.l	d0,-20(a6)
if_end_0_68000:
	; var result1: i32
	moveq	#0,d0
	move.l	d0,-24(a6)
	; var result2: i32
	moveq	#0,d0
	move.l	d0,-28(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_1_68000
	bra	if_end_1_68000
if_then_1_68000:
	; %t13 = add
	move.l	-4(a6),d0
	moveq	#0,d1
	add.l	d1,d0
	; %t14 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; Store to result1
	move.l	d0,-24(a6)
	; %t15 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; Store to result2
	move.l	d0,-28(a6)
if_end_1_68000:
	; %t16 = add
	move.l	-4(a6),d0
	move.l	-8(a6),d1
	add.l	d1,d0
	; %t17 = add
	move.l	-16(a6),d1
	add.l	d1,d0
	; %t18 = add
	move.l	-20(a6),d1
	add.l	d1,d0
	; %t19 = add
	move.l	-24(a6),d1
	add.l	d1,d0
	; %t20 = add
	move.l	-28(a6),d1
	add.l	d1,d0
	; Exit with return code (main function)
	move.l	d0,-(sp)		; Push exit code
	jsr	_exit		; Terminate process (noreturn)

	; Function: main_68020
_main_68020:
	link	a6,#-28
	; var x: i32
	moveq	#5,d0
	move.l	d0,-4(a6)
	; %t0 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; %t1 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; var a: i32
	moveq	#100,d0
	move.l	d0,-8(a6)
	; %t2 = add
	move.l	-8(a6),d0
	moveq	#50,d1
	add.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; %t3 = sub
	move.l	-8(a6),d0
	moveq	#30,d1
	sub.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; %t4 = mul
	move.l	-8(a6),d0
	moveq	#2,d1
	muls.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; %t5 = div
	move.l	-8(a6),d0
	moveq	#3,d1
	divs.l	d1,d0
	; Store to a
	move.l	d0,-8(a6)
	; Store to a
	move.l	d0,-8(a6)
	; var b: u32
	move.l	#255,d0
	move.l	d0,-12(a6)
	; %t7 = and
	move.l	-12(a6),d0
	moveq	#15,d1
	and.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; %t8 = or
	move.l	-12(a6),d0
	move.l	#240,d1
	or.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; %t9 = xor
	move.l	-12(a6),d0
	move.l	#170,d1
	eor.l	d1,d0
	; Store to b
	move.l	d0,-12(a6)
	; var c: u32
	moveq	#1,d0
	move.l	d0,-16(a6)
	; %t10 = shl
	move.l	-16(a6),d0
	lsl.l	#4,d0
	; Store to c
	move.l	d0,-16(a6)
	; %t11 = shr
	move.l	-16(a6),d0
	lsr.l	#2,d0
	; Store to c
	move.l	d0,-16(a6)
	; var z: i32
	moveq	#20,d0
	move.l	d0,-20(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_0_68020
	bra	if_end_0_68020
if_then_0_68020:
	; %t12 = sub
	move.l	-20(a6),d0
	moveq	#1,d1
	sub.l	d1,d0
	; Store to z
	move.l	d0,-20(a6)
if_end_0_68020:
	; var result1: i32
	moveq	#0,d0
	move.l	d0,-24(a6)
	; var result2: i32
	moveq	#0,d0
	move.l	d0,-28(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_1_68020
	bra	if_end_1_68020
if_then_1_68020:
	; %t13 = add
	move.l	-4(a6),d0
	moveq	#0,d1
	add.l	d1,d0
	; %t14 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; Store to result1
	move.l	d0,-24(a6)
	; %t15 = add
	move.l	-4(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-4(a6)
	; Store to result2
	move.l	d0,-28(a6)
if_end_1_68020:
	; %t16 = add
	move.l	-4(a6),d0
	move.l	-8(a6),d1
	add.l	d1,d0
	; %t17 = add
	move.l	-16(a6),d1
	add.l	d1,d0
	; %t18 = add
	move.l	-20(a6),d1
	add.l	d1,d0
	; %t19 = add
	move.l	-24(a6),d1
	add.l	d1,d0
	; %t20 = add
	move.l	-28(a6),d1
	add.l	d1,d0
	; Exit with return code (main function)
	move.l	d0,-(sp)		; Push exit code
	jsr	_exit		; Terminate process (noreturn)

	; Function: main_68060
_main_68060:
	link	a6,#-56
	; var x: i32
	moveq	#5,d0
	move.l	d0,-8(a6)
	; %t0 = add
	move.l	-8(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-8(a6)
	; %t1 = add
	move.l	-8(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-8(a6)
	; var a: i32
	moveq	#100,d0
	move.l	d0,-16(a6)
	; %t2 = add
	move.l	-16(a6),d0
	moveq	#50,d1
	add.l	d1,d0
	; Store to a
	move.l	d0,-16(a6)
	; %t3 = sub
	move.l	-16(a6),d0
	moveq	#30,d1
	sub.l	d1,d0
	; Store to a
	move.l	d0,-16(a6)
	; %t4 = mul
	move.l	-16(a6),d0
	moveq	#2,d1
	; 68060 optimization: x * 2 = x << 1
	add.l	d0,d0
	; Store to a
	move.l	d0,-16(a6)
	; %t5 = div
	move.l	-16(a6),d0
	moveq	#3,d1
	divs.l	d1,d0
	; WARNING: 68060 has very slow 32-bit divide (>70 cycles); avoid if possible
	; Store to a
	move.l	d0,-16(a6)
	; Store to a
	move.l	d0,-16(a6)
	; var b: u32
	move.l	#255,d0
	move.l	d0,-24(a6)
	; %t7 = and
	move.l	-24(a6),d0
	moveq	#15,d1
	and.l	d1,d0
	; Store to b
	move.l	d0,-24(a6)
	; %t8 = or
	move.l	-24(a6),d0
	move.l	#240,d1
	or.l	d1,d0
	; Store to b
	move.l	d0,-24(a6)
	; %t9 = xor
	move.l	-24(a6),d0
	move.l	#170,d1
	eor.l	d1,d0
	; Store to b
	move.l	d0,-24(a6)
	; var c: u32
	moveq	#1,d0
	move.l	d0,-32(a6)
	; %t10 = shl
	move.l	-32(a6),d0
	lsl.l	#4,d0
	; Store to c
	move.l	d0,-32(a6)
	; %t11 = shr
	move.l	-32(a6),d0
	lsr.l	#2,d0
	; Store to c
	move.l	d0,-32(a6)
	; var z: i32
	moveq	#20,d0
	move.l	d0,-40(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_0_68060
	bra	if_end_0_68060
if_then_0_68060:
	; %t12 = sub
	move.l	-40(a6),d0
	moveq	#1,d1
	sub.l	d1,d0
	; Store to z
	move.l	d0,-40(a6)
if_end_0_68060:
	; var result1: i32
	moveq	#0,d0
	move.l	d0,-48(a6)
	; var result2: i32
	moveq	#0,d0
	move.l	d0,-56(a6)
	moveq	#1,d0
	tst.l	d0
	bne	if_then_1_68060
	bra	if_end_1_68060
if_then_1_68060:
	; %t13 = add
	move.l	-8(a6),d0
	moveq	#0,d1
	add.l	d1,d0
	; %t14 = add
	move.l	-8(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-8(a6)
	; Store to result1
	move.l	d0,-48(a6)
	; %t15 = add
	move.l	-8(a6),d0
	moveq	#1,d1
	add.l	d1,d0
	; Store to x
	move.l	d0,-8(a6)
	; Store to result2
	move.l	d0,-56(a6)
if_end_1_68060:
	; %t16 = add
	move.l	-8(a6),d0
	move.l	-16(a6),d1
	add.l	d1,d0
	; %t17 = add
	move.l	-32(a6),d1
	add.l	d1,d0
	; %t18 = add
	move.l	-40(a6),d1
	add.l	d1,d0
	; %t19 = add
	move.l	-48(a6),d1
	add.l	d1,d0
	; %t20 = add
	move.l	-56(a6),d1
	add.l	d1,d0
	; Exit with return code (main function)
	move.l	d0,-(sp)		; Push exit code
	jsr	_exit		; Terminate process (noreturn)

