apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: novus

resources:
  - namespace.yaml
  - website-deployment.yaml
  - website-service.yaml
  - website-ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/barryw/novuslang-website
    newTag: latest
