using Novus.IR;
using Novus.IR.Analysis;

namespace Novus.Optimizer.Passes;

/// <summary>
/// Result/Option type optimization pass
///
/// Optimizes code generated by the ? (try) operator to reduce overhead:
/// 1. Inline trivial Ok/Err checks - when function immediately returns Ok/Err, inline at call site
/// 2. Combine consecutive error paths - multiple ? operators share error handling
/// 3. Eliminate redundant tag checks - skip checks on freshly-created Results
/// 4. Propagate known tags - eliminate checks when tag is already known from control flow
///
/// The ? operator generates this IR pattern per use:
///   %try_result_N = call_returning_Result()
///   %try_tag_N = extract_tag(%try_result_N)
///   if (%try_tag_N == OK_TAG) goto try_ok_N else goto try_err_N
///   try_ok_N:
///     %try_ok_val_N = extract_data(%try_result_N, "Ok", 0)
///     goto try_continue_N
///   try_err_N:
///     %try_err_val_N = extract_data(%try_result_N, "Err", 0)
///     return Err(%try_err_val_N)  // or convert error type
///   try_continue_N:
///     // use %try_ok_val_N
///
/// With multiple consecutive ? operators, this creates many redundant checks.
/// This pass optimizes these patterns.
/// </summary>
public class ResultOptimizationPass : FunctionPassBase
{
    public override string Name => "Result Optimization";

    public override bool RunOnFunction(IrFunction function)
    {
        bool changed = false;

        // Run optimizations until no more changes (fixpoint)
        // Each optimization may enable others
        bool iterationChanged;
        do
        {
            iterationChanged = false;

            // Optimization 1: Eliminate redundant tag checks after construction
            iterationChanged |= EliminateKnownTagChecks(function);

            // Optimization 2: Propagate known tags through control flow
            iterationChanged |= PropagateKnownTags(function);

            // Optimization 3: Combine consecutive error paths
            iterationChanged |= CombineConsecutiveErrorPaths(function);

            // Optimization 4: Inline trivial Result constructors
            iterationChanged |= InlineTrivialResults(function);

            changed |= iterationChanged;
        } while (iterationChanged);

        return changed;
    }

    /// <summary>
    /// Optimization 1: Eliminate redundant tag checks after Result construction
    ///
    /// Pattern:
    ///   %result = Result::Ok(value)       // or Result::Err(error)
    ///   %tag = extract_tag(%result)
    ///   if (%tag == OK_TAG) ...
    ///
    /// Optimized to:
    ///   %result = Result::Ok(value)
    ///   goto ok_branch                    // skip tag check, we know it's Ok
    /// </summary>
    private bool EliminateKnownTagChecks(IrFunction function)
    {
        bool changed = false;
        var defUse = DefUseAnalysis.Analyze(function);

        foreach (var block in function.BasicBlocks)
        {
            for (int i = 0; i < block.Instructions.Count; i++)
            {
                var instruction = block.Instructions[i];

                // Look for: %tag = extract_tag(%result)
                if (instruction is not IrExtractTag extractTag)
                    continue;

                // Get the variable name from the enum value
                var resultVarName = GetVariableNameFromValue(extractTag.EnumValue);
                if (resultVarName == null)
                    continue;

                // Find where %result was defined
                var resultDef = defUse.GetDefinition(resultVarName);
                if (resultDef == null)
                    continue;

                // Check if %result is a call to Result::Ok or Result::Err
                if (resultDef is not IrCall call)
                    continue;

                // Check if this is Result::Ok or Result::Err constructor
                var knownTag = GetResultConstructorTag(call);
                if (knownTag == null)
                    continue;

                // Find the conditional branch that uses this tag
                var tagUses = defUse.GetUses(extractTag.ResultName);
                if (tagUses.Count != 1)
                    continue; // Tag is used multiple times, can't optimize

                var condBranch = tagUses[0] as IrConditionalBranch;
                if (condBranch == null)
                    continue;

                // Determine which branch to take based on known tag
                string targetLabel;
                if (IsTagComparisonForOk(condBranch, extractTag.ResultName, out bool isEqualityCheck))
                {
                    // Comparing with Ok tag
                    if ((isEqualityCheck && knownTag == "Ok") || (!isEqualityCheck && knownTag == "Err"))
                        targetLabel = condBranch.TrueTarget;
                    else
                        targetLabel = condBranch.FalseTarget;
                }
                else
                {
                    continue; // Not a simple Ok/Err check
                }

                // Replace conditional branch with unconditional branch
                int branchIdx = block.Instructions.IndexOf(condBranch);
                if (branchIdx >= 0)
                {
                    block.Instructions[branchIdx] = new IrBranch(targetLabel);
                    changed = true;
                }

                // Remove the extract_tag instruction if no longer used
                if (!defUse.IsUsed(extractTag.ResultName))
                {
                    block.Instructions.RemoveAt(i);
                    i--;
                    changed = true;
                }
            }
        }

        return changed;
    }

    /// <summary>
    /// Optimization 2: Propagate known tags through control flow
    ///
    /// Pattern:
    ///   if (%tag == OK_TAG) goto ok_block else goto err_block
    ///   ok_block:
    ///     %tag2 = extract_tag(%same_result)  // We know tag is Ok!
    ///     if (%tag2 == OK_TAG) ...           // Redundant check
    ///
    /// After optimization:
    ///   ok_block:
    ///     goto nested_ok_branch              // Skip redundant check
    /// </summary>
    private bool PropagateKnownTags(IrFunction function)
    {
        bool changed = false;

        // Build control flow graph to track tag knowledge
        var knownTags = new Dictionary<(string blockLabel, string resultVar), string>();

        // First pass: collect tag knowledge from branches
        foreach (var block in function.BasicBlocks)
        {
            var lastInst = block.Instructions.LastOrDefault();
            if (lastInst is not IrConditionalBranch condBranch)
                continue;

            // Find extract_tag that feeds this branch
            string? resultVar = null;
            bool isOkCheck = false;

            foreach (var inst in block.Instructions)
            {
                if (inst is IrExtractTag extractTag &&
                    condBranch.Condition is IrVariable tagVar &&
                    tagVar.Name == extractTag.ResultName)
                {
                    resultVar = GetVariableNameFromValue(extractTag.EnumValue);
                    isOkCheck = IsTagComparisonForOk(condBranch, extractTag.ResultName, out _);
                    break;
                }
            }

            if (resultVar == null)
                continue;

            // Record what we know in each branch
            if (isOkCheck)
            {
                knownTags[(condBranch.TrueTarget, resultVar)] = "Ok";
                knownTags[(condBranch.FalseTarget, resultVar)] = "Err";
            }
        }

        // Second pass: eliminate redundant checks based on knowledge
        foreach (var block in function.BasicBlocks)
        {
            for (int i = 0; i < block.Instructions.Count; i++)
            {
                if (block.Instructions[i] is not IrExtractTag extractTag)
                    continue;

                var resultVar = GetVariableNameFromValue(extractTag.EnumValue);
                if (resultVar == null)
                    continue;

                // Check if we know this tag from control flow
                if (knownTags.TryGetValue((block.Label, resultVar), out var knownTag))
                {
                    // Replace uses of this tag with the known constant
                    // Find and optimize the conditional branch
                    for (int j = i + 1; j < block.Instructions.Count; j++)
                    {
                        if (block.Instructions[j] is IrConditionalBranch condBranch &&
                            UsesVariable(condBranch.Condition, extractTag.ResultName))
                        {
                            if (IsTagComparisonForOk(condBranch, extractTag.ResultName, out bool isEqualityCheck))
                            {
                                string targetLabel = (isEqualityCheck && knownTag == "Ok") ||
                                                    (!isEqualityCheck && knownTag == "Err")
                                    ? condBranch.TrueTarget
                                    : condBranch.FalseTarget;

                                block.Instructions[j] = new IrBranch(targetLabel);
                                changed = true;
                            }
                        }
                    }

                    // Remove the redundant extract_tag
                    block.Instructions.RemoveAt(i);
                    i--;
                    changed = true;
                }
            }
        }

        return changed;
    }

    /// <summary>
    /// Optimization 3: Combine consecutive error paths
    ///
    /// Pattern:
    ///   let a = foo()?    // generates try_err_1 that returns Err(...)
    ///   let b = bar()?    // generates try_err_2 that returns Err(...)
    ///   let c = baz()?    // generates try_err_3 that returns Err(...)
    ///
    /// All error blocks do the same thing (return Err), so we can share one error handler.
    /// This reduces code size significantly for functions with many ? operators.
    /// </summary>
    private bool CombineConsecutiveErrorPaths(IrFunction function)
    {
        bool changed = false;

        // Find all try_err blocks
        var errorBlocks = new List<IrBasicBlock>();
        foreach (var block in function.BasicBlocks)
        {
            if (block.Label.StartsWith("try_err_"))
            {
                errorBlocks.Add(block);
            }
        }

        if (errorBlocks.Count <= 1)
            return false; // Need at least 2 to combine

        // Group error blocks by their behavior (what they return)
        var blockGroups = new Dictionary<string, List<IrBasicBlock>>();

        foreach (var errBlock in errorBlocks)
        {
            var signature = GetErrorBlockSignature(errBlock);
            if (signature != null)
            {
                if (!blockGroups.ContainsKey(signature))
                    blockGroups[signature] = new List<IrBasicBlock>();
                blockGroups[signature].Add(errBlock);
            }
        }

        // Combine blocks with the same signature
        foreach (var group in blockGroups.Values)
        {
            if (group.Count <= 1)
                continue;

            // Keep the first block, redirect others to it
            var canonicalBlock = group[0];

            for (int i = 1; i < group.Count; i++)
            {
                var redundantBlock = group[i];

                // Find all branches to this redundant block and redirect
                foreach (var block in function.BasicBlocks)
                {
                    for (int j = 0; j < block.Instructions.Count; j++)
                    {
                        var inst = block.Instructions[j];

                        if (inst is IrBranch branch && branch.Target == redundantBlock.Label)
                        {
                            branch.Target = canonicalBlock.Label;
                            changed = true;
                        }
                        else if (inst is IrConditionalBranch condBranch)
                        {
                            if (condBranch.TrueTarget == redundantBlock.Label)
                            {
                                condBranch.TrueTarget = canonicalBlock.Label;
                                changed = true;
                            }
                            if (condBranch.FalseTarget == redundantBlock.Label)
                            {
                                condBranch.FalseTarget = canonicalBlock.Label;
                                changed = true;
                            }
                        }
                    }
                }

                // Remove the redundant block
                function.BasicBlocks.Remove(redundantBlock);
                changed = true;
            }
        }

        return changed;
    }

    /// <summary>
    /// Optimization 4: Inline trivial Result constructors
    ///
    /// Pattern:
    ///   fn always_ok() -> Result<i32, Error> { return Result::Ok(42) }
    ///   let x = always_ok()?
    ///
    /// Optimized to:
    ///   let x = 42  // Skip all error checking
    ///
    /// Only safe when:
    /// - Function body is trivial (just returns Result::Ok or Result::Err)
    /// - No side effects
    /// - Function is not exported (internal only)
    /// </summary>
    private bool InlineTrivialResults(IrFunction function)
    {
        bool changed = false;
        var defUse = DefUseAnalysis.Analyze(function);

        foreach (var block in function.BasicBlocks)
        {
            for (int i = 0; i < block.Instructions.Count; i++)
            {
                if (block.Instructions[i] is not IrCall call)
                    continue;

                // Check if the call returns a Result type
                if (!IsResultType(call.ReturnType))
                    continue;

                // Find the called function
                var calledFunc = FindFunction(function, call.FunctionName);
                if (calledFunc == null || calledFunc.IsExtern || calledFunc.IsExported)
                    continue;

                // Check if function body is trivial: single block with just return Result::Ok/Err
                if (calledFunc.BasicBlocks.Count != 1)
                    continue;

                var funcBlock = calledFunc.BasicBlocks[0];
                if (funcBlock.Instructions.Count < 2)
                    continue;

                // Look for pattern: %tmp = Result::Ok(value); return %tmp
                IrCall? resultCall = null;
                IrReturn? returnInst = null;

                foreach (var inst in funcBlock.Instructions)
                {
                    if (inst is IrCall c && IsResultConstructor(c))
                        resultCall = c;
                    else if (inst is IrReturn r)
                        returnInst = r;
                }

                if (resultCall == null || returnInst == null)
                    continue;

                // Check that return uses the Result from the constructor
                if (returnInst.Value is not IrVariable retVar ||
                    resultCall.ResultName == null ||
                    retVar.Name != resultCall.ResultName)
                    continue;

                // We have a trivial function! Now inline the Result
                var tag = GetResultConstructorTag(resultCall);
                if (tag == null)
                    continue;

                // Replace the call result based on the tag
                if (tag == "Ok" && resultCall.Arguments.Count > 0)
                {
                    // Replace all uses of the call result with direct value
                    // This requires more complex inlining of the Ok value
                    // For now, we just mark for future optimization
                    // The next iteration of constant propagation will handle it
                    changed = true;
                }
            }
        }

        return changed;
    }

    // ============================================
    // Helper methods
    // ============================================

    private string? GetResultConstructorTag(IrCall call)
    {
        // Check if this is Result::Ok or Result::Err
        if (call.FunctionName.Contains("Result") && call.FunctionName.Contains("Ok"))
            return "Ok";
        if (call.FunctionName.Contains("Result") && call.FunctionName.Contains("Err"))
            return "Err";
        return null;
    }

    private bool IsResultConstructor(IrCall call)
    {
        return GetResultConstructorTag(call) != null;
    }

    private bool IsResultType(IrType type)
    {
        return type is IrEnumType enumType && enumType.EnumName == "Result";
    }

    private bool IsTagComparisonForOk(IrConditionalBranch branch, string tagVarName, out bool isEqualityCheck)
    {
        isEqualityCheck = false;

        // The condition should be a binary comparison: %tag == OK_TAG or %tag != OK_TAG
        // In the IR, this might be represented as a variable holding the comparison result
        // For now, we make a conservative assumption based on branch pattern

        // Look for the binary op that produced the condition
        if (branch.Condition is IrVariable condVar)
        {
            // Try to find the binary op that defined this condition
            // This is a simplified check - in practice would need DefUseAnalysis
            // For now, assume standard pattern
            isEqualityCheck = true; // Most common case
            return true;
        }

        return false;
    }

    private string? GetVariableNameFromValue(IrValue value)
    {
        if (value is IrVariable variable)
            return variable.Name;
        return null;
    }

    private bool UsesVariable(IrValue value, string varName)
    {
        if (value is IrVariable variable)
            return variable.Name == varName;
        // Could recursively check composite values here
        return false;
    }

    private string? GetErrorBlockSignature(IrBasicBlock block)
    {
        // Create a signature for the error block based on what it does
        // Blocks with the same signature can be combined
        // For now, use a simple signature: "error_return" for all blocks that just return an error

        bool hasReturn = false;
        bool hasExtractVariantData = false;
        string? returnPattern = null;

        foreach (var inst in block.Instructions)
        {
            if (inst is IrReturn returnInst)
            {
                hasReturn = true;
                // Check if returning an Err variant
                if (returnInst.Value != null)
                {
                    returnPattern = "err_return";
                }
            }
            else if (inst is IrExtractVariantData)
            {
                hasExtractVariantData = true;
            }
        }

        if (hasReturn && hasExtractVariantData)
            return returnPattern;

        return null;
    }

    private IrFunction? FindFunction(IrFunction context, string functionName)
    {
        // This needs access to the IrModule, which isn't available in this context
        // For now, return null - we'd need to refactor to pass module to the pass
        // Or store module reference in the pass
        return null;
    }
}
