using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Novus.IR;

namespace Novus.Codegen;

/// <summary>
/// C code generator for Novus.
/// Generates C99 code from Novus IR that can be compiled with VBCC.
/// Target: AmigaOS 2.0+ (68020+) using +aos68k -c99
/// </summary>
public class CCodeGenerator
{
    private readonly IrModule _module;
    private readonly List<IrStringLiteral> _stringLiterals;
    private readonly string _cpuTarget;
    private readonly string _fpuMode;
    private readonly StringBuilder _output;
    private readonly HashSet<string> _requiredProtoHeaders;
    private readonly HashSet<string>? _explicitEntryPoints;
    private readonly bool _useSharedTypesHeader;

    // Track which variables have been declared in the current function
    // to avoid redeclaration errors when the same variable is assigned in multiple branches
    private HashSet<string> _declaredVariables = new();

    public CCodeGenerator(IrModule module, List<IrStringLiteral> stringLiterals, string cpuTarget, string fpuMode, HashSet<string>? explicitEntryPoints = null, bool useSharedTypesHeader = false)
    {
        _module = module;
        _stringLiterals = stringLiterals;
        _cpuTarget = cpuTarget;
        _fpuMode = fpuMode;
        _output = new StringBuilder();
        _requiredProtoHeaders = new HashSet<string>();
        _explicitEntryPoints = explicitEntryPoints;
        _useSharedTypesHeader = useSharedTypesHeader;
    }

    /// <summary>
    /// Generate shared types header from a type registry.
    /// This header contains all type definitions used across modules.
    /// </summary>
    public static string GenerateSharedTypesHeader(TypeRegistry typeRegistry)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Novus Standard Library - Shared Type Definitions");
        sb.AppendLine("// Auto-generated - do not edit");
        sb.AppendLine("//");
        sb.AppendLine("// This header contains all type definitions used by Novus stdlib.");
        sb.AppendLine("// Each function is compiled separately and includes this header.");
        sb.AppendLine();
        sb.AppendLine("#ifndef NOVUS_TYPES_H");
        sb.AppendLine("#define NOVUS_TYPES_H");
        sb.AppendLine();
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine();

        // String type (always include - it's fundamental)
        sb.AppendLine("// String type (fat pointer: pointer + length)");
        sb.AppendLine("typedef struct {");
        sb.AppendLine("    uint8_t* ptr;");
        sb.AppendLine("    int32_t len;");
        sb.AppendLine("} String;");
        sb.AppendLine();

        var codegen = new CCodeGenerator(new IrModule(), new List<IrStringLiteral>(), "68020", "auto");

        // Struct types
        if (typeRegistry.StructTypes.Any())
        {
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// Struct Types");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();

            foreach (var structType in typeRegistry.StructTypes.OrderBy(s => s.Name))
            {
                codegen.EmitStructTypeToBuilder(sb, structType);
            }
        }

        // Enum types
        if (typeRegistry.EnumTypes.Any())
        {
            sb.AppendLine("// ============================================================================");
            sb.AppendLine("// Enum Types");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();

            foreach (var enumType in typeRegistry.EnumTypes.OrderBy(e => e.Name))
            {
                codegen.EmitEnumTypeToBuilder(sb, enumType);
            }
        }

        sb.AppendLine("#endif // NOVUS_TYPES_H");

        return sb.ToString();
    }

    /// <summary>
    /// Generate a single-function C file for library modules.
    /// This enables the linker to pull in only the functions that are actually used.
    /// </summary>
    public string GenerateFunctionFile(IrFunction function)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine($"// Generated by Novus compiler");
        sb.AppendLine($"// Function: {function.Name}");
        sb.AppendLine($"// Module: {_module.Functions.FirstOrDefault()?.Name ?? "unknown"}");
        sb.AppendLine();

        // Include shared types header
        if (_useSharedTypesHeader)
        {
            sb.AppendLine("#include \"novus_types.h\"");
            sb.AppendLine();
        }
        else
        {
            // Fallback: include basic headers
            sb.AppendLine("#include <stdint.h>");
            sb.AppendLine("#include <stdbool.h>");
            sb.AppendLine();
        }

        // Extern declarations for functions this function calls
        var calledFunctions = GetCalledFunctions(function);
        if (calledFunctions.Count > 0)
        {
            sb.AppendLine("// External function declarations");
            foreach (var calledFunc in calledFunctions.OrderBy(f => f))
            {
                var funcObj = _module.Functions.FirstOrDefault(f => f.Name == calledFunc);
                if (funcObj != null)
                {
                    var returnType = GetCType(funcObj.ReturnType);
                    var parameters = GetParameterList(funcObj);
                    sb.AppendLine($"extern {returnType} {MangleName(calledFunc)}({parameters});");
                }
            }
            sb.AppendLine();
        }

        // Function implementation
        // EmitFunction writes to _output, so we need to capture its output
        // We'll temporarily redirect output
        var functionOutput = new StringBuilder();
        EmitFunctionToBuilder(functionOutput, function);
        sb.Append(functionOutput.ToString());

        return sb.ToString();
    }

    /// <summary>
    /// Emit a function to a specific StringBuilder (used for per-function file generation)
    /// </summary>
    private void EmitFunctionToBuilder(StringBuilder targetBuilder, IrFunction function)
    {
        var returnType = GetCType(function.ReturnType);
        var parameters = GetParameterList(function);
        var funcName = MangleName(function.Name);

        // Special case: main must return 'int' for VBCC compatibility
        if (funcName == "main" && returnType == "int32_t")
        {
            returnType = "int";
        }

        targetBuilder.AppendLine($"{returnType} {funcName}({parameters}) {{");

        // Emit all basic blocks
        foreach (var block in function.BasicBlocks)
        {
            foreach (var instruction in block.Instructions)
            {
                // We need to emit instructions to the target builder
                // For now, just call EmitInstruction and capture from _output
                // This is a limitation - ideally EmitInstruction would take a StringBuilder
                var beforeLength = _output.Length;
                EmitInstruction(instruction);
                var emitted = _output.ToString().Substring(beforeLength);
                targetBuilder.Append(emitted);

                // Clear what we just appended from _output
                _output.Length = beforeLength;
            }
        }

        targetBuilder.AppendLine("}");
    }

    /// <summary>
    /// Helper to emit enum type to a specific StringBuilder (for shared header generation)
    /// </summary>
    private void EmitEnumTypeToBuilder(StringBuilder sb, IrEnumType enumType)
    {
        var enumName = MangleName(enumType);

        // Check if this enum has any associated data
        bool hasAnyData = enumType.Variants.Any(v => v.HasAssociatedData);

        sb.AppendLine($"// Enum: {enumType.Name}");

        if (!hasAnyData)
        {
            // OPTIMIZATION: For enums with no associated data, use plain C enum
            sb.AppendLine($"typedef enum {{");
            for (int i = 0; i < enumType.Variants.Count; i++)
            {
                var variant = enumType.Variants[i];
                var comma = i < enumType.Variants.Count - 1 ? "," : "";
                sb.AppendLine($"    {enumName}_{variant.Name} = {variant.Tag}{comma}");
            }
            sb.AppendLine($"}} {enumName};");
            sb.AppendLine();
            return;
        }

        // For enums WITH associated data, use the full struct+union representation
        sb.AppendLine($"enum {enumName}_Tag {{");
        for (int i = 0; i < enumType.Variants.Count; i++)
        {
            var variant = enumType.Variants[i];
            var comma = i < enumType.Variants.Count - 1 ? "," : "";
            sb.AppendLine($"    {enumName}_{variant.Name} = {variant.Tag}{comma}");
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine($"union {enumName}_Data {{");
        foreach (var variant in enumType.Variants)
        {
            if (variant.HasAssociatedData)
            {
                sb.AppendLine($"    struct {{");
                for (int i = 0; i < variant.AssociatedData.Count; i++)
                {
                    var dataType = GetCType(variant.AssociatedData[i]);
                    sb.AppendLine($"        {dataType} _{i};");
                }
                sb.AppendLine($"    }} {variant.Name};");
            }
        }
        sb.AppendLine("};");
        sb.AppendLine();

        sb.AppendLine($"typedef struct {{");
        sb.AppendLine($"    enum {enumName}_Tag tag;");
        sb.AppendLine($"    union {enumName}_Data data;");
        sb.AppendLine($"}} {enumName};");
        sb.AppendLine();
    }

    /// <summary>
    /// Helper to emit struct type to a specific StringBuilder (for shared header generation)
    /// </summary>
    private void EmitStructTypeToBuilder(StringBuilder sb, IrStructType structType)
    {
        var structName = MangleName(structType);

        sb.AppendLine($"// Struct: {structType.Name}");
        sb.AppendLine($"typedef struct {{");

        foreach (var field in structType.Fields)
        {
            var fieldType = GetCType(field.Type);
            sb.AppendLine($"    {fieldType} {field.Name};");
        }

        sb.AppendLine($"}} {structName};");
        sb.AppendLine();
    }

    /// <summary>
    /// Get list of functions called by this function
    /// </summary>
    private HashSet<string> GetCalledFunctions(IrFunction function)
    {
        var called = new HashSet<string>();

        foreach (var block in function.BasicBlocks)
        {
            foreach (var instruction in block.Instructions)
            {
                if (instruction is IrCall call)
                {
                    called.Add(call.FunctionName);
                }
            }
        }

        return called;
    }

    public string Generate()
    {
        // First pass: detect which AmigaOS libraries are used
        DetectRequiredProtoHeaders();

        // Second pass: analyze reachable functions (dead code elimination)
        var reachableFunctions = AnalyzeReachableFunctions();

        EmitHeaders();
        EmitTypedefs(reachableFunctions);
        EmitStringLiterals();
        EmitForwardDeclarations(reachableFunctions);
        EmitFunctions(reachableFunctions);

        return _output.ToString();
    }

    private void DetectRequiredProtoHeaders()
    {
        // Map of function names to their proto headers
        var protoMap = new Dictionary<string, string>
        {
            // exec.library
            ["AllocMem"] = "exec",
            ["FreeMem"] = "exec",
            ["OpenLibrary"] = "exec",
            ["CloseLibrary"] = "exec",
            ["FindTask"] = "exec",
            ["Wait"] = "exec",
            ["Signal"] = "exec",
            ["AllocSignal"] = "exec",
            ["FreeSignal"] = "exec",

            // dos.library
            ["Output"] = "dos",
            ["Input"] = "dos",
            ["Write"] = "dos",
            ["Read"] = "dos",
            ["Open"] = "dos",
            ["Close"] = "dos",
            ["Printf"] = "dos",
        };

        foreach (var function in _module.Functions)
        {
            if (function.IsExtern && protoMap.TryGetValue(function.Name, out var header))
            {
                _requiredProtoHeaders.Add(header);
            }
        }
    }

    /// <summary>
    /// Analyze which functions are reachable from entry points (main or public functions).
    /// This enables dead code elimination - we only emit functions that can actually be called.
    /// </summary>
    private HashSet<string> AnalyzeReachableFunctions()
    {
        var reachable = new HashSet<string>();
        var worklist = new Queue<string>();

        // Find entry points:
        // 1. If there's a main function, it's the primary entry point
        // 2. If explicit entry points are provided, use only those
        // 3. For library modules without explicit entry points, include public functions
        var entryPoints = new List<IrFunction>();
        var mainFunc = _module.Functions.FirstOrDefault(f => f.Name == "main" && !f.IsExtern);
        if (mainFunc != null)
        {
            entryPoints.Add(mainFunc);
        }
        else if (_explicitEntryPoints != null)
        {
            // Use explicit entry points (for smart cross-module DCE)
            entryPoints.AddRange(_module.Functions.Where(f =>
                _explicitEntryPoints.Contains(f.Name) && !f.IsExtern && f.BasicBlocks.Count > 0));
        }
        else
        {
            // For library modules: include ALL public functions as potential entry points
            // This is conservative but safe - the linker can eliminate truly unused functions
            entryPoints.AddRange(_module.Functions.Where(f => f.IsPublic && !f.IsExtern && f.BasicBlocks.Count > 0));
        }

        // Start BFS from entry points
        foreach (var entry in entryPoints)
        {
            reachable.Add(entry.Name);
            worklist.Enqueue(entry.Name);
        }

        // Build call graph and mark reachable functions
        while (worklist.Count > 0)
        {
            var currentName = worklist.Dequeue();
            var currentFunc = _module.Functions.FirstOrDefault(f => f.Name == currentName);
            if (currentFunc == null)
                continue;

            // Scan all instructions for function calls
            foreach (var block in currentFunc.BasicBlocks)
            {
                foreach (var instruction in block.Instructions)
                {
                    if (instruction is IrCall call)
                    {
                        // Mark called function as reachable
                        if (!reachable.Contains(call.FunctionName))
                        {
                            reachable.Add(call.FunctionName);

                            // If it's a function in this module (not extern), add to worklist
                            var calledFunc = _module.Functions.FirstOrDefault(f => f.Name == call.FunctionName && !f.IsExtern);
                            if (calledFunc != null)
                            {
                                worklist.Enqueue(call.FunctionName);
                            }
                        }
                    }
                }
            }
        }

        // NOTE: For library modules (no main), we conservatively include all public functions
        // as potential entry points. True dead code elimination across modules requires either:
        // 1. Whole-program analysis (compile all modules together)
        // 2. Link-time optimization (linker eliminates unused functions)
        // 3. Explicit import tracking (only emit explicitly imported functions)
        // For now, we rely on the linker's --gc-sections to eliminate truly unused code.

        return reachable;
    }

    private void EmitHeaders()
    {
        _output.AppendLine("// Generated by Novus compiler");
        _output.AppendLine("// Target: AmigaOS 2.0+ (68020+), C99");
        _output.AppendLine();

        if (_useSharedTypesHeader)
        {
            _output.AppendLine("#include \"novus_types.h\"");
            _output.AppendLine();
        }
        else
        {
            _output.AppendLine("#include <stdint.h>");
            _output.AppendLine("#include <stdbool.h>");
            _output.AppendLine();
        }

        // Don't emit proto headers - we'll use assembly stubs with i32 signatures
        // This avoids fighting VBCC's type system (BPTR, CONST_STRPTR, etc.)
        // Our assembly stubs handle the conversions from i32 to proper AmigaOS types
    }

    private void EmitTypedefs(HashSet<string> reachableFunctions)
    {
        // Skip type definitions if using shared types header
        if (_useSharedTypesHeader)
            return;

        // String type (fat pointer)
        _output.AppendLine("// String type (fat pointer: pointer + length)");
        _output.AppendLine("typedef struct {");
        _output.AppendLine("    uint8_t* ptr;");
        _output.AppendLine("    int32_t len;");
        _output.AppendLine("} String;");
        _output.AppendLine();

        // Emit enum types (only those used by reachable functions)
        EmitEnumTypes(reachableFunctions);

        // TODO: Add struct typedefs as needed
    }

    private void EmitEnumTypes(HashSet<string> reachableFunctions)
    {
        // Collect all unique enum types used in reachable functions only
        var enumTypes = new HashSet<IrEnumType>();

        // Scan only reachable functions for enum types
        foreach (var function in _module.Functions.Where(f => reachableFunctions.Contains(f.Name)))
        {
            if (function.ReturnType is IrEnumType enumRet)
                enumTypes.Add(enumRet);

            foreach (var param in function.Parameters)
            {
                if (param.Type is IrEnumType enumParam)
                    enumTypes.Add(enumParam);
            }

            // Scan local variables
            foreach (var local in function.LocalVariables)
            {
                if (local.Type is IrEnumType enumLocal)
                    enumTypes.Add(enumLocal);
            }

            // Scan instructions for enum values
            foreach (var block in function.BasicBlocks)
            {
                foreach (var instruction in block.Instructions)
                {
                    // Check for IrLocalDecl with enum types
                    if (instruction is IrLocalDecl localDecl && localDecl.Type is IrEnumType enumDeclType)
                        enumTypes.Add(enumDeclType);

                    // Check for IrMatch to get the matched enum type
                    if (instruction is IrMatch match && match.MatchValue.Type is IrEnumType matchEnumType)
                        enumTypes.Add(matchEnumType);
                }
            }
        }

        if (enumTypes.Count == 0)
            return;

        _output.AppendLine("// Enum types");

        // Emit enums in dependency order: simple (unit variant) enums first, then enums with associated data
        // This ensures that if Result<T, DosError> uses DosError, DosError is defined first
        var simpleEnums = new List<IrEnumType>();
        var complexEnums = new List<IrEnumType>();

        foreach (var enumType in enumTypes)
        {
            bool hasAssociatedData = enumType.Variants.Any(v => v.AssociatedData.Count > 0);
            if (hasAssociatedData)
            {
                complexEnums.Add(enumType);
            }
            else
            {
                simpleEnums.Add(enumType);
            }
        }

        // Emit simple enums first
        foreach (var enumType in simpleEnums)
        {
            EmitEnumType(enumType);
        }

        // Then emit complex enums
        foreach (var enumType in complexEnums)
        {
            EmitEnumType(enumType);
        }
    }

    private void EmitEnumType(IrEnumType enumType)
    {
        var enumName = MangleName(enumType);

        // Check if this enum has any associated data
        bool hasAnyData = enumType.Variants.Any(v => v.HasAssociatedData);

        _output.AppendLine($"// Enum: {enumType.Name}");

        if (!hasAnyData)
        {
            // OPTIMIZATION: For enums with no associated data, use plain C enum
            // This saves space by avoiding the struct+union overhead
            _output.AppendLine($"typedef enum {{");
            for (int i = 0; i < enumType.Variants.Count; i++)
            {
                var variant = enumType.Variants[i];
                var comma = i < enumType.Variants.Count - 1 ? "," : "";
                _output.AppendLine($"    {enumName}_{variant.Name} = {variant.Tag}{comma}");
            }
            _output.AppendLine($"}} {enumName};");
            _output.AppendLine();
            return;
        }

        // For enums WITH associated data, use the full struct+union representation

        // Emit variant tag enum
        _output.AppendLine($"enum {enumName}_Tag {{");
        for (int i = 0; i < enumType.Variants.Count; i++)
        {
            var variant = enumType.Variants[i];
            var comma = i < enumType.Variants.Count - 1 ? "," : "";
            _output.AppendLine($"    {enumName}_{variant.Name} = {variant.Tag}{comma}");
        }
        _output.AppendLine("};");
        _output.AppendLine();

        // Emit union for variant data
        _output.AppendLine($"union {enumName}_Data {{");
        foreach (var variant in enumType.Variants)
        {
            if (variant.HasAssociatedData)
            {
                _output.AppendLine($"    struct {{");
                for (int i = 0; i < variant.AssociatedData.Count; i++)
                {
                    var dataType = GetCType(variant.AssociatedData[i]);
                    _output.AppendLine($"        {dataType} _{i};");
                }
                _output.AppendLine($"    }} {variant.Name};");
            }
        }
        _output.AppendLine("};");
        _output.AppendLine();

        // Emit main struct
        _output.AppendLine($"typedef struct {{");
        _output.AppendLine($"    enum {enumName}_Tag tag;");
        _output.AppendLine($"    union {enumName}_Data data;");
        _output.AppendLine($"}} {enumName};");
        _output.AppendLine();
    }

    private void EmitStringLiterals()
    {
        if (_stringLiterals.Count == 0)
            return;

        _output.AppendLine("// String literals");
        for (int i = 0; i < _stringLiterals.Count; i++)
        {
            var literal = _stringLiterals[i];
            // Escape string for C
            var escaped = EscapeString(literal.Value);
            _output.AppendLine($"static const char {literal.Label}[] = \"{escaped}\";");
        }
        _output.AppendLine();
    }

    private string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private void EmitForwardDeclarations(HashSet<string> reachableFunctions)
    {
        // Always emit DOS initialization function declaration if we have a main function
        // DOS might be used transitively through other modules
        bool hasMain = _module.Functions.Any(f => f.Name == "main");
        if (hasMain)
        {
            _output.AppendLine("// DOS library initialization");
            _output.AppendLine("extern void __dos_init(void);");
            _output.AppendLine();
        }

        // Emit extern declarations for extern functions (from FFI) - but only if they're reachable
        var externFunctions = _module.Functions
            .Where(f => f.IsExtern && reachableFunctions.Contains(f.Name))
            .ToList();
        if (externFunctions.Count > 0)
        {
            _output.AppendLine("// External function declarations (FFI)");
            foreach (var function in externFunctions)
            {
                var returnType = GetCType(function.ReturnType);
                var parameters = GetParameterList(function);
                _output.AppendLine($"extern {returnType} {MangleName(function.Name)}({parameters});");
            }
            _output.AppendLine();
        }

        // Find all cross-module function calls (functions called but not defined in this module)
        // Only consider calls from reachable functions
        var crossModuleCalls = new Dictionary<string, (IrType ReturnType, List<IrType> ParameterTypes)>();
        // Only consider functions with implementations as "defined" - imported functions have no basic blocks
        var definedFunctionNames = new HashSet<string>(
            _module.Functions
                .Where(f => !f.IsExtern && f.BasicBlocks.Count > 0)
                .Select(f => f.Name)
        );

        // Also include extern functions as "defined" since they're FFI declarations
        var externFunctionNames = new HashSet<string>(
            _module.Functions.Where(f => f.IsExtern).Select(f => f.Name)
        );

        // Only scan reachable functions for cross-module calls
        foreach (var function in _module.Functions.Where(f => f.BasicBlocks.Count > 0 && reachableFunctions.Contains(f.Name)))
        {
            foreach (var block in function.BasicBlocks)
            {
                foreach (var instruction in block.Instructions)
                {
                    if (instruction is IrCall call)
                    {
                        // If this function is not defined in current module, not an extern, and not already tracked
                        if (!definedFunctionNames.Contains(call.FunctionName) &&
                            !externFunctionNames.Contains(call.FunctionName) &&
                            !crossModuleCalls.ContainsKey(call.FunctionName))
                        {
                            // Extract parameter types from call arguments
                            var paramTypes = call.Arguments.Select(arg => arg.Type).ToList();
                            crossModuleCalls[call.FunctionName] = (call.ReturnType, paramTypes);
                        }
                    }
                }
            }
        }

        // Emit cross-module function declarations
        if (crossModuleCalls.Count > 0)
        {
            _output.AppendLine("// Cross-module function declarations");
            foreach (var (funcName, (returnType, paramTypes)) in crossModuleCalls)
            {
                var cReturnType = GetCType(returnType);
                var parameters = paramTypes.Count == 0 ? "void" :
                    string.Join(", ", paramTypes.Select((type, index) => $"{GetCType(type)} p{index}"));
                _output.AppendLine($"{cReturnType} {MangleName(funcName)}({parameters});");
            }
            _output.AppendLine();
        }

        // Only emit declarations for reachable implemented functions
        var implementedFunctions = _module.Functions
            .Where(f => !f.IsExtern && f.BasicBlocks.Count > 0 && reachableFunctions.Contains(f.Name))
            .ToList();

        if (implementedFunctions.Count == 0)
            return;

        _output.AppendLine("// Forward declarations");
        foreach (var function in implementedFunctions)
        {
            var returnType = GetCType(function.ReturnType);
            var parameters = GetParameterList(function);

            // Special case: main returns int, not int32_t
            if (function.Name == "main" && returnType == "int32_t")
            {
                returnType = "int";
            }

            _output.AppendLine($"{returnType} {MangleName(function.Name)}({parameters});");
        }
        _output.AppendLine();
    }

    private void EmitFunctions(HashSet<string> reachableFunctions)
    {
        // Only emit reachable functions (dead code elimination)
        var implementedFunctions = _module.Functions
            .Where(f => !f.IsExtern && f.BasicBlocks.Count > 0 && reachableFunctions.Contains(f.Name))
            .ToList();

        if (implementedFunctions.Count == 0)
            return;

        _output.AppendLine("// Function implementations");
        foreach (var function in implementedFunctions)
        {
            EmitFunction(function);
            _output.AppendLine();
        }
    }

    private void EmitFunction(IrFunction function)
    {
        // Clear declared variables for this function
        _declaredVariables.Clear();

        var returnType = GetCType(function.ReturnType);
        var parameters = GetParameterList(function);
        var funcName = MangleName(function.Name);

        // Special case: main must return 'int' for VBCC compatibility
        if (funcName == "main" && returnType == "int32_t")
        {
            returnType = "int";
        }

        _output.AppendLine($"{returnType} {funcName}({parameters}) {{");

        // If this is main, always initialize DOS library
        // This is safe even if DOS isn't used (it's idempotent)
        // We do this because DOS might be used transitively through other modules
        if (funcName == "main")
        {
            _output.AppendLine("    __dos_init();");
        }

        // Emit function body
        foreach (var block in function.BasicBlocks)
        {
            EmitBasicBlock(block);
        }

        // Close any pending match arm scope
        if (_inMatchArmScope)
        {
            _output.AppendLine("    }");
            _inMatchArmScope = false;
        }

        _output.AppendLine("}");
    }

    private void EmitBasicBlock(IrBasicBlock block)
    {
        foreach (var instruction in block.Instructions)
        {
            EmitInstruction(instruction);
        }
    }

    private void EmitInstruction(IrInstruction instruction)
    {
        switch (instruction)
        {
            case IrLocalDecl localDecl:
                EmitLocalDecl(localDecl);
                break;

            case IrStore store:
                EmitStore(store);
                break;

            case IrBinaryOp binaryOp:
                EmitBinaryOp(binaryOp);
                break;

            case IrCall call:
                EmitCall(call);
                break;

            case IrLabel label:
                EmitLabel(label);
                break;

            case IrBranch branch:
                EmitBranch(branch);
                break;

            case IrConditionalBranch condBranch:
                EmitConditionalBranch(condBranch);
                break;

            case IrReturn returnInst:
                EmitReturn(returnInst);
                break;

            case IrMatch match:
                EmitMatch(match);
                break;

            case IrExtractTag extractTag:
                EmitExtractTag(extractTag);
                break;

            case IrExtractVariantData extractData:
                EmitExtractVariantData(extractData);
                break;

            case IrMemberAccess memberAccess:
                EmitMemberAccess(memberAccess);
                break;

            default:
                _output.AppendLine($"    // TODO: {instruction.GetType().Name}");
                break;
        }
    }

    private void EmitLocalDecl(IrLocalDecl localDecl)
    {
        var cType = GetCType(localDecl.Type);
        var varName = SanitizeVariableName(localDecl.Name);
        var initValue = EmitValue(localDecl.InitialValue);

        // Check if this variable has already been declared in this function
        if (_declaredVariables.Contains(varName))
        {
            // Already declared - emit assignment only
            var initType = GetCType(localDecl.InitialValue.Type);
            if (initType != cType)
            {
                _output.AppendLine($"    {varName} = ({cType}){initValue};");
            }
            else
            {
                _output.AppendLine($"    {varName} = {initValue};");
            }
        }
        else
        {
            // First declaration - emit with type
            var initType = GetCType(localDecl.InitialValue.Type);
            if (initType != cType)
            {
                _output.AppendLine($"    {cType} {varName} = ({cType}){initValue};");
            }
            else
            {
                _output.AppendLine($"    {cType} {varName} = {initValue};");
            }
            _declaredVariables.Add(varName);
        }
    }

    private void EmitStore(IrStore store)
    {
        var varName = SanitizeVariableName(store.VariableName);
        var value = EmitValue(store.Value);

        // TODO: Add cast support if needed for Store
        _output.AppendLine($"    {varName} = {value};");
    }

    private void EmitBinaryOp(IrBinaryOp binaryOp)
    {
        var cType = GetCType(binaryOp.Type);
        var resultName = SanitizeVariableName(binaryOp.ResultName);
        var left = EmitValue(binaryOp.Left);
        var right = EmitValue(binaryOp.Right);
        var op = GetBinaryOperator(binaryOp.Operation);

        _output.AppendLine($"    {cType} {resultName} = {left} {op} {right};");
    }

    private void EmitCall(IrCall call)
    {
        // For FFI calls, we need to cast pointer arguments to int32_t
        var function = _module.Functions.FirstOrDefault(f => f.Name == call.FunctionName);
        var args = new List<string>();

        for (int i = 0; i < call.Arguments.Count; i++)
        {
            var arg = call.Arguments[i];
            var argValue = EmitValue(arg);

            // If this is an extern FFI function and the parameter expects i32 but we have a pointer, cast it
            if (function != null && function.IsExtern && i < function.Parameters.Count)
            {
                var paramType = function.Parameters[i].Type;
                // If parameter is i32 and argument is a pointer, add cast
                if (paramType is IrIntType intType && intType.BitWidth == 32 && arg is IrVariable variable)
                {
                    // Check if the variable is a pointer type
                    // For now, we'll add the cast unconditionally for pointers
                    argValue = $"(int32_t){argValue}";
                }
            }

            args.Add(argValue);
        }

        var callExpr = $"{MangleName(call.FunctionName)}({string.Join(", ", args)})";

        if (call.ResultName != null)
        {
            var cType = GetCType(call.ReturnType);
            var resultName = SanitizeVariableName(call.ResultName);
            _output.AppendLine($"    {cType} {resultName} = {callExpr};");
        }
        else
        {
            _output.AppendLine($"    {callExpr};");
        }
    }

    private bool _inMatchArmScope = false;

    private void EmitLabel(IrLabel label)
    {
        // Close previous match arm scope if needed
        if (_inMatchArmScope && (label.Name.StartsWith("match_arm_") || label.Name.StartsWith("match_end_") || label.Name.StartsWith("match_check_")))
        {
            _output.AppendLine("    }");
            _inMatchArmScope = false;
        }

        // Emit label (unindented for C style)
        // Add empty statement to ensure valid C (labels must be followed by a statement)
        _output.AppendLine($"{label.Name}:;");

        // Open new scope for match arms
        if (label.Name.StartsWith("match_arm_"))
        {
            _output.AppendLine("    {");
            _inMatchArmScope = true;
        }
    }

    private void EmitBranch(IrBranch branch)
    {
        _output.AppendLine($"    goto {branch.Target};");
    }

    private void EmitConditionalBranch(IrConditionalBranch condBranch)
    {
        var condition = EmitValue(condBranch.Condition);
        _output.AppendLine($"    if ({condition}) goto {condBranch.TrueTarget};");
        if (!string.IsNullOrEmpty(condBranch.FalseTarget))
        {
            _output.AppendLine($"    goto {condBranch.FalseTarget};");
        }
    }

    private void EmitReturn(IrReturn returnInst)
    {
        if (returnInst.Value != null)
        {
            var value = EmitValue(returnInst.Value);
            _output.AppendLine($"    return {value};");
        }
        else
        {
            _output.AppendLine("    return;");
        }
    }

    private void EmitMatch(IrMatch match)
    {
        var matchValue = EmitValue(match.MatchValue);
        var enumType = match.MatchValue.Type as IrEnumType;

        if (enumType == null)
            throw new InvalidOperationException("Match expression must be on an enum type");

        var enumName = MangleName(enumType);

        // Switch on the tag
        _output.AppendLine($"    switch ({matchValue}.tag) {{");

        foreach (var arm in match.Arms)
        {
            if (arm.Pattern is IrVariantPattern variantPattern)
            {
                _output.AppendLine($"    case {enumName}_{variantPattern.VariantName}:");

                // Extract bound variables from variant data
                for (int i = 0; i < variantPattern.BoundVariables.Count; i++)
                {
                    var boundVar = variantPattern.BoundVariables[i];
                    var variant = enumType.GetVariant(variantPattern.VariantName);
                    if (variant != null && i < variant.AssociatedData.Count)
                    {
                        var dataType = GetCType(variant.AssociatedData[i]);
                        _output.AppendLine($"        {dataType} {boundVar} = {matchValue}.data.{variantPattern.VariantName}._{i};");
                    }
                }

                _output.AppendLine($"        goto {arm.TargetLabel};");
            }
            else if (arm.Pattern is IrWildcardPattern)
            {
                _output.AppendLine($"    default:");
                _output.AppendLine($"        goto {arm.TargetLabel};");
            }
        }

        _output.AppendLine("    }");
    }

    private void EmitExtractTag(IrExtractTag extractTag)
    {
        var enumValue = EmitValue(extractTag.EnumValue);
        var resultName = SanitizeVariableName(extractTag.ResultName);

        var enumType = extractTag.EnumValue.Type as IrEnumType;
        if (enumType == null)
            throw new InvalidOperationException("ExtractTag must be on an enum type");

        // Check if this enum has any associated data
        bool hasAnyData = enumType.Variants.Any(v => v.HasAssociatedData);

        if (!hasAnyData)
        {
            // OPTIMIZATION: For plain enums, the value IS the tag
            _output.AppendLine($"    int32_t {resultName} = {enumValue};");
        }
        else
        {
            // For enums with associated data, extract the tag field
            _output.AppendLine($"    int32_t {resultName} = {enumValue}.tag;");
        }
    }

    private void EmitExtractVariantData(IrExtractVariantData extractData)
    {
        var enumValue = EmitValue(extractData.EnumValue);
        var resultName = SanitizeVariableName(extractData.ResultName);
        var enumType = extractData.EnumValue.Type as IrEnumType;

        if (enumType == null)
            throw new InvalidOperationException("ExtractVariantData must be on an enum type");

        var dataType = GetCType(extractData.DataType);

        // Extract data from the specific variant
        _output.AppendLine($"    {dataType} {resultName} = {enumValue}.data.{extractData.VariantName}._{extractData.DataIndex};");
    }

    private void EmitMemberAccess(IrMemberAccess memberAccess)
    {
        var structValue = EmitValue(memberAccess.Struct);
        var resultName = SanitizeVariableName(memberAccess.ResultName);
        var fieldType = GetCType(memberAccess.FieldType);

        _output.AppendLine($"    {fieldType} {resultName} = {structValue}.{memberAccess.FieldName};");
    }

    private string EmitValue(IrValue value)
    {
        return value switch
        {
            IrConstant constant => constant.Value.ToString(),
            IrBoolConstant boolConst => boolConst.Value ? "true" : "false",
            IrVariable variable => SanitizeVariableName(variable.Name),
            IrStringLiteral stringLit => $"(String){{ .ptr = (uint8_t*){stringLit.Label}, .len = {stringLit.Length} }}",
            IrEnumValue enumValue => EmitEnumValue(enumValue),
            IrBorrowValue borrowValue => $"&{EmitValue(borrowValue.BorrowedValue)}",
            IrDereferenceValue derefValue => $"(*{EmitValue(derefValue.PointerValue)})",
            IrStructLiteral structLit => EmitStructLiteral(structLit),
            _ => throw new NotSupportedException($"Unsupported value type: {value.GetType().Name}")
        };
    }

    private string EmitStructLiteral(IrStructLiteral structLit)
    {
        var structType = structLit.Type as IrStructType;
        if (structType == null)
            throw new InvalidOperationException("StructLiteral must have IrStructType");

        var typeName = GetCType(structType);
        var fields = structLit.FieldValues
            .Select(kvp => $".{kvp.Key} = {EmitValue(kvp.Value)}")
            .ToList();

        return $"({typeName}){{ {string.Join(", ", fields)} }}";
    }

    private string EmitEnumValue(IrEnumValue enumValue)
    {
        var enumType = enumValue.Type as IrEnumType;
        if (enumType == null)
            throw new InvalidOperationException("EnumValue must have IrEnumType");

        var enumName = MangleName(enumType);

        // Check if this enum has any associated data
        bool hasAnyData = enumType.Variants.Any(v => v.HasAssociatedData);

        // OPTIMIZATION: For enums with no associated data, just emit the enum constant
        if (!hasAnyData)
        {
            return $"{enumName}_{enumValue.VariantName}";
        }

        // For enums WITH associated data, use compound literal
        var result = $"({enumName}){{ .tag = {enumName}_{enumValue.VariantName}";

        if (enumValue.AssociatedValues.Count > 0)
        {
            result += ", .data = { ." + enumValue.VariantName + " = {";
            for (int i = 0; i < enumValue.AssociatedValues.Count; i++)
            {
                var assocValue = EmitValue(enumValue.AssociatedValues[i]);
                result += $" ._{i} = {assocValue}";
                if (i < enumValue.AssociatedValues.Count - 1)
                    result += ",";
            }
            result += " } }";
        }

        result += " }";
        return result;
    }

    private int _tempCounter = 0;

    private string SanitizeVariableName(string name)
    {
        // Convert IR temp variable names (%t0, %t1, etc.) to valid C identifiers (_t0, _t1, etc.)
        if (name.StartsWith("%"))
        {
            return "_" + name.Substring(1);
        }
        return name;
    }

    private string GetBinaryOperator(IrBinaryOp.OpKind operation)
    {
        return operation switch
        {
            IrBinaryOp.OpKind.Add => "+",
            IrBinaryOp.OpKind.Sub => "-",
            IrBinaryOp.OpKind.Mul => "*",
            IrBinaryOp.OpKind.Div => "/",
            IrBinaryOp.OpKind.Mod => "%",
            IrBinaryOp.OpKind.And => "&",
            IrBinaryOp.OpKind.Or => "|",
            IrBinaryOp.OpKind.Xor => "^",
            IrBinaryOp.OpKind.Shl => "<<",
            IrBinaryOp.OpKind.Shr => ">>",
            IrBinaryOp.OpKind.Eq => "==",
            IrBinaryOp.OpKind.Ne => "!=",
            IrBinaryOp.OpKind.Lt => "<",
            IrBinaryOp.OpKind.Le => "<=",
            IrBinaryOp.OpKind.Gt => ">",
            IrBinaryOp.OpKind.Ge => ">=",
            _ => throw new NotSupportedException($"Unsupported binary operation: {operation}")
        };
    }

    private string GetCType(IrType type)
    {
        return type switch
        {
            IrIntType intType => intType.IsSigned
                ? intType.BitWidth switch
                {
                    8 => "int8_t",
                    16 => "int16_t",
                    32 => "int32_t",
                    64 => "int64_t",
                    _ => throw new NotSupportedException($"Unsupported int width: {intType.BitWidth}")
                }
                : intType.BitWidth switch
                {
                    8 => "uint8_t",
                    16 => "uint16_t",
                    32 => "uint32_t",
                    64 => "uint64_t",
                    _ => throw new NotSupportedException($"Unsupported uint width: {intType.BitWidth}")
                },
            IrBoolType => "bool",
            IrVoidType => "void",
            IrPointerType ptrType => $"{GetCType(ptrType.PointeeType)}*",
            IrStringType => "String",
            IrEnumType enumType => MangleName(enumType),
            IrStructType structType => MangleName(structType),
            IrArrayType arrayType => $"{GetCType(arrayType.ElementType)}*",  // Arrays as pointers for now
            IrReferenceType refType => $"{GetCType(refType.PointeeType)}*",  // References as pointers
            IrMutReferenceType mutRefType => $"{GetCType(mutRefType.PointeeType)}*",  // Mut references as pointers
            _ => throw new NotSupportedException($"Unsupported type: {type.GetType().Name}")
        };
    }

    private string GetParameterList(IrFunction function)
    {
        if (function.Parameters.Count == 0)
            return "void";

        var parameters = function.Parameters
            .Select(p => $"{GetCType(p.Type)} {p.Name}")
            .ToList();

        return string.Join(", ", parameters);
    }

    private string MangleName(string name)
    {
        // For now, keep names simple
        // TODO: Handle generic instantiations, modules, etc.
        return name.Replace("::", "_");
    }

    private string MangleName(IrEnumType enumType)
    {
        // Use CacheKey for monomorphized generics, otherwise use EnumName
        var name = enumType.CacheKey ?? enumType.EnumName;

        // Sanitize for C identifier:
        // Option<i32> -> Option_i32
        // Result<i32, *u8> -> Result_i32_ptr_u8
        return name.Replace("::", "_")
                   .Replace("<", "_")
                   .Replace(">", "")
                   .Replace(",", "")
                   .Replace("*", "ptr_")
                   .Replace(" ", "");
    }

    private string MangleName(IrStructType structType)
    {
        // Use CacheKey for monomorphized generics, otherwise use Name
        var name = structType.CacheKey ?? structType.Name;

        // Sanitize for C identifier:
        // Vec<i32> -> Vec_i32
        // HashMap<String, i32> -> HashMap_String_i32
        return name.Replace("::", "_")
                   .Replace("<", "_")
                   .Replace(">", "")
                   .Replace(",", "")
                   .Replace("*", "ptr_")
                   .Replace(" ", "");
    }
}
