using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Novus.IR;

namespace Novus.Codegen;

/// <summary>
/// C code generator for Novus.
/// Generates C99 code from Novus IR that can be compiled with VBCC.
/// Target: AmigaOS 2.0+ (68020+) using +aos68k -c99
/// </summary>
public class CCodeGenerator
{
    private readonly IrModule _module;
    private readonly List<IrStringLiteral> _stringLiterals;
    private readonly string _cpuTarget;
    private readonly string _fpuMode;
    private readonly StringBuilder _output;
    private readonly HashSet<string> _requiredProtoHeaders;

    public CCodeGenerator(IrModule module, List<IrStringLiteral> stringLiterals, string cpuTarget, string fpuMode)
    {
        _module = module;
        _stringLiterals = stringLiterals;
        _cpuTarget = cpuTarget;
        _fpuMode = fpuMode;
        _output = new StringBuilder();
        _requiredProtoHeaders = new HashSet<string>();
    }

    public string Generate()
    {
        // First pass: detect which AmigaOS libraries are used
        DetectRequiredProtoHeaders();

        EmitHeaders();
        EmitTypedefs();
        EmitStringLiterals();
        EmitForwardDeclarations();
        EmitFunctions();

        return _output.ToString();
    }

    private void DetectRequiredProtoHeaders()
    {
        // Map of function names to their proto headers
        var protoMap = new Dictionary<string, string>
        {
            // exec.library
            ["AllocMem"] = "exec",
            ["FreeMem"] = "exec",
            ["OpenLibrary"] = "exec",
            ["CloseLibrary"] = "exec",
            ["FindTask"] = "exec",
            ["Wait"] = "exec",
            ["Signal"] = "exec",
            ["AllocSignal"] = "exec",
            ["FreeSignal"] = "exec",

            // dos.library
            ["Output"] = "dos",
            ["Input"] = "dos",
            ["Write"] = "dos",
            ["Read"] = "dos",
            ["Open"] = "dos",
            ["Close"] = "dos",
            ["Printf"] = "dos",
        };

        foreach (var function in _module.Functions)
        {
            if (function.IsExtern && protoMap.TryGetValue(function.Name, out var header))
            {
                _requiredProtoHeaders.Add(header);
            }
        }
    }

    private void EmitHeaders()
    {
        _output.AppendLine("// Generated by Novus compiler");
        _output.AppendLine("// Target: AmigaOS 2.0+ (68020+), C99");
        _output.AppendLine();
        _output.AppendLine("#include <stdint.h>");
        _output.AppendLine("#include <stdbool.h>");
        _output.AppendLine();

        // Don't emit proto headers - we'll use assembly stubs with i32 signatures
        // This avoids fighting VBCC's type system (BPTR, CONST_STRPTR, etc.)
        // Our assembly stubs handle the conversions from i32 to proper AmigaOS types
    }

    private void EmitTypedefs()
    {
        // String type (fat pointer)
        _output.AppendLine("// String type (fat pointer: pointer + length)");
        _output.AppendLine("typedef struct {");
        _output.AppendLine("    uint8_t* ptr;");
        _output.AppendLine("    int32_t len;");
        _output.AppendLine("} String;");
        _output.AppendLine();

        // Emit enum types
        EmitEnumTypes();

        // TODO: Add struct typedefs as needed
    }

    private void EmitEnumTypes()
    {
        // Collect all unique enum types used in the module
        var enumTypes = new HashSet<IrEnumType>();

        // Scan functions for enum types
        foreach (var function in _module.Functions)
        {
            if (function.ReturnType is IrEnumType enumRet)
                enumTypes.Add(enumRet);

            foreach (var param in function.Parameters)
            {
                if (param.Type is IrEnumType enumParam)
                    enumTypes.Add(enumParam);
            }

            // Scan local variables
            foreach (var local in function.LocalVariables)
            {
                if (local.Type is IrEnumType enumLocal)
                    enumTypes.Add(enumLocal);
            }

            // Scan instructions for enum values
            foreach (var block in function.BasicBlocks)
            {
                foreach (var instruction in block.Instructions)
                {
                    // Check for IrLocalDecl with enum types
                    if (instruction is IrLocalDecl localDecl && localDecl.Type is IrEnumType enumDeclType)
                        enumTypes.Add(enumDeclType);

                    // Check for IrMatch to get the matched enum type
                    if (instruction is IrMatch match && match.MatchValue.Type is IrEnumType matchEnumType)
                        enumTypes.Add(matchEnumType);
                }
            }
        }

        if (enumTypes.Count == 0)
            return;

        _output.AppendLine("// Enum types");

        foreach (var enumType in enumTypes)
        {
            EmitEnumType(enumType);
        }
    }

    private void EmitEnumType(IrEnumType enumType)
    {
        var enumName = MangleName(enumType.Name);

        // Emit variant tag enum
        _output.AppendLine($"// Enum: {enumType.Name}");
        _output.AppendLine($"enum {enumName}_Tag {{");
        for (int i = 0; i < enumType.Variants.Count; i++)
        {
            var variant = enumType.Variants[i];
            var comma = i < enumType.Variants.Count - 1 ? "," : "";
            _output.AppendLine($"    {enumName}_{variant.Name} = {variant.Tag}{comma}");
        }
        _output.AppendLine("};");
        _output.AppendLine();

        // Emit union for variant data
        _output.AppendLine($"union {enumName}_Data {{");
        foreach (var variant in enumType.Variants)
        {
            if (variant.HasAssociatedData)
            {
                _output.AppendLine($"    struct {{");
                for (int i = 0; i < variant.AssociatedData.Count; i++)
                {
                    var dataType = GetCType(variant.AssociatedData[i]);
                    _output.AppendLine($"        {dataType} _{i};");
                }
                _output.AppendLine($"    }} {variant.Name};");
            }
        }
        _output.AppendLine("};");
        _output.AppendLine();

        // Emit main struct
        _output.AppendLine($"typedef struct {{");
        _output.AppendLine($"    enum {enumName}_Tag tag;");
        _output.AppendLine($"    union {enumName}_Data data;");
        _output.AppendLine($"}} {enumName};");
        _output.AppendLine();
    }

    private void EmitStringLiterals()
    {
        if (_stringLiterals.Count == 0)
            return;

        _output.AppendLine("// String literals");
        for (int i = 0; i < _stringLiterals.Count; i++)
        {
            var literal = _stringLiterals[i];
            // Escape string for C
            var escaped = EscapeString(literal.Value);
            _output.AppendLine($"static const char {literal.Label}[] = \"{escaped}\";");
        }
        _output.AppendLine();
    }

    private string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private void EmitForwardDeclarations()
    {
        // If DOS functions are used, emit DOS initialization function
        bool usesDOS = _module.Functions.Any(f => f.IsExtern && _requiredProtoHeaders.Contains("dos"));
        if (usesDOS)
        {
            _output.AppendLine("// DOS library initialization");
            _output.AppendLine("extern void __dos_init(void);");
            _output.AppendLine();
        }

        // Emit extern declarations for extern functions (from FFI)
        var externFunctions = _module.Functions.Where(f => f.IsExtern).ToList();
        if (externFunctions.Count > 0)
        {
            _output.AppendLine("// External function declarations (FFI)");
            foreach (var function in externFunctions)
            {
                var returnType = GetCType(function.ReturnType);
                var parameters = GetParameterList(function);
                _output.AppendLine($"extern {returnType} {MangleName(function.Name)}({parameters});");
            }
            _output.AppendLine();
        }

        // Only emit declarations for functions with implementations
        var implementedFunctions = _module.Functions
            .Where(f => !f.IsExtern && f.BasicBlocks.Count > 0)
            .ToList();

        if (implementedFunctions.Count == 0)
            return;

        _output.AppendLine("// Forward declarations");
        foreach (var function in implementedFunctions)
        {
            var returnType = GetCType(function.ReturnType);
            var parameters = GetParameterList(function);

            // Special case: main returns int, not int32_t
            if (function.Name == "main" && returnType == "int32_t")
            {
                returnType = "int";
            }

            _output.AppendLine($"{returnType} {MangleName(function.Name)}({parameters});");
        }
        _output.AppendLine();
    }

    private void EmitFunctions()
    {
        // Count non-extern functions that have implementations
        var implementedFunctions = _module.Functions
            .Where(f => !f.IsExtern && f.BasicBlocks.Count > 0)
            .ToList();

        if (implementedFunctions.Count == 0)
            return;

        _output.AppendLine("// Function implementations");
        foreach (var function in implementedFunctions)
        {
            EmitFunction(function);
            _output.AppendLine();
        }
    }

    private void EmitFunction(IrFunction function)
    {
        var returnType = GetCType(function.ReturnType);
        var parameters = GetParameterList(function);
        var funcName = MangleName(function.Name);

        // Special case: main must return 'int' for VBCC compatibility
        if (funcName == "main" && returnType == "int32_t")
        {
            returnType = "int";
        }

        _output.AppendLine($"{returnType} {funcName}({parameters}) {{");

        // If this is main and DOS is used, initialize DOS library first
        bool usesDOS = _module.Functions.Any(f => f.IsExtern && _requiredProtoHeaders.Contains("dos"));
        if (funcName == "main" && usesDOS)
        {
            _output.AppendLine("    __dos_init();");
        }

        // Emit function body
        foreach (var block in function.BasicBlocks)
        {
            EmitBasicBlock(block);
        }

        _output.AppendLine("}");
    }

    private void EmitBasicBlock(IrBasicBlock block)
    {
        foreach (var instruction in block.Instructions)
        {
            EmitInstruction(instruction);
        }
    }

    private void EmitInstruction(IrInstruction instruction)
    {
        switch (instruction)
        {
            case IrLocalDecl localDecl:
                EmitLocalDecl(localDecl);
                break;

            case IrStore store:
                EmitStore(store);
                break;

            case IrBinaryOp binaryOp:
                EmitBinaryOp(binaryOp);
                break;

            case IrCall call:
                EmitCall(call);
                break;

            case IrLabel label:
                EmitLabel(label);
                break;

            case IrBranch branch:
                EmitBranch(branch);
                break;

            case IrConditionalBranch condBranch:
                EmitConditionalBranch(condBranch);
                break;

            case IrReturn returnInst:
                EmitReturn(returnInst);
                break;

            case IrMatch match:
                EmitMatch(match);
                break;

            case IrExtractTag extractTag:
                EmitExtractTag(extractTag);
                break;

            case IrExtractVariantData extractData:
                EmitExtractVariantData(extractData);
                break;

            default:
                _output.AppendLine($"    // TODO: {instruction.GetType().Name}");
                break;
        }
    }

    private void EmitLocalDecl(IrLocalDecl localDecl)
    {
        var cType = GetCType(localDecl.Type);
        var varName = SanitizeVariableName(localDecl.Name);
        var initValue = EmitValue(localDecl.InitialValue);
        _output.AppendLine($"    {cType} {varName} = {initValue};");
    }

    private void EmitStore(IrStore store)
    {
        var varName = SanitizeVariableName(store.VariableName);
        var value = EmitValue(store.Value);
        _output.AppendLine($"    {varName} = {value};");
    }

    private void EmitBinaryOp(IrBinaryOp binaryOp)
    {
        var cType = GetCType(binaryOp.Type);
        var resultName = SanitizeVariableName(binaryOp.ResultName);
        var left = EmitValue(binaryOp.Left);
        var right = EmitValue(binaryOp.Right);
        var op = GetBinaryOperator(binaryOp.Operation);

        _output.AppendLine($"    {cType} {resultName} = {left} {op} {right};");
    }

    private void EmitCall(IrCall call)
    {
        // For FFI calls, we need to cast pointer arguments to int32_t
        var function = _module.Functions.FirstOrDefault(f => f.Name == call.FunctionName);
        var args = new List<string>();

        for (int i = 0; i < call.Arguments.Count; i++)
        {
            var arg = call.Arguments[i];
            var argValue = EmitValue(arg);

            // If this is an extern FFI function and the parameter expects i32 but we have a pointer, cast it
            if (function != null && function.IsExtern && i < function.Parameters.Count)
            {
                var paramType = function.Parameters[i].Type;
                // If parameter is i32 and argument is a pointer, add cast
                if (paramType is IrIntType intType && intType.BitWidth == 32 && arg is IrVariable variable)
                {
                    // Check if the variable is a pointer type
                    // For now, we'll add the cast unconditionally for pointers
                    argValue = $"(int32_t){argValue}";
                }
            }

            args.Add(argValue);
        }

        var callExpr = $"{MangleName(call.FunctionName)}({string.Join(", ", args)})";

        if (call.ResultName != null)
        {
            var cType = GetCType(call.ReturnType);
            var resultName = SanitizeVariableName(call.ResultName);
            _output.AppendLine($"    {cType} {resultName} = {callExpr};");
        }
        else
        {
            _output.AppendLine($"    {callExpr};");
        }
    }

    private void EmitLabel(IrLabel label)
    {
        // Emit label (unindented for C style)
        // Add empty statement to ensure valid C (labels must be followed by a statement)
        _output.AppendLine($"{label.Name}:;");
    }

    private void EmitBranch(IrBranch branch)
    {
        _output.AppendLine($"    goto {branch.Target};");
    }

    private void EmitConditionalBranch(IrConditionalBranch condBranch)
    {
        var condition = EmitValue(condBranch.Condition);
        _output.AppendLine($"    if ({condition}) goto {condBranch.TrueTarget};");
        if (!string.IsNullOrEmpty(condBranch.FalseTarget))
        {
            _output.AppendLine($"    goto {condBranch.FalseTarget};");
        }
    }

    private void EmitReturn(IrReturn returnInst)
    {
        if (returnInst.Value != null)
        {
            var value = EmitValue(returnInst.Value);
            _output.AppendLine($"    return {value};");
        }
        else
        {
            _output.AppendLine("    return;");
        }
    }

    private void EmitMatch(IrMatch match)
    {
        var matchValue = EmitValue(match.MatchValue);
        var enumType = match.MatchValue.Type as IrEnumType;

        if (enumType == null)
            throw new InvalidOperationException("Match expression must be on an enum type");

        var enumName = MangleName(enumType.Name);

        // Switch on the tag
        _output.AppendLine($"    switch ({matchValue}.tag) {{");

        foreach (var arm in match.Arms)
        {
            if (arm.Pattern is IrVariantPattern variantPattern)
            {
                _output.AppendLine($"    case {enumName}_{variantPattern.VariantName}:");

                // Extract bound variables from variant data
                for (int i = 0; i < variantPattern.BoundVariables.Count; i++)
                {
                    var boundVar = variantPattern.BoundVariables[i];
                    var variant = enumType.GetVariant(variantPattern.VariantName);
                    if (variant != null && i < variant.AssociatedData.Count)
                    {
                        var dataType = GetCType(variant.AssociatedData[i]);
                        _output.AppendLine($"        {dataType} {boundVar} = {matchValue}.data.{variantPattern.VariantName}._{i};");
                    }
                }

                _output.AppendLine($"        goto {arm.TargetLabel};");
            }
            else if (arm.Pattern is IrWildcardPattern)
            {
                _output.AppendLine($"    default:");
                _output.AppendLine($"        goto {arm.TargetLabel};");
            }
        }

        _output.AppendLine("    }");
    }

    private void EmitExtractTag(IrExtractTag extractTag)
    {
        var enumValue = EmitValue(extractTag.EnumValue);
        var resultName = SanitizeVariableName(extractTag.ResultName);
        _output.AppendLine($"    int32_t {resultName} = {enumValue}.tag;");
    }

    private void EmitExtractVariantData(IrExtractVariantData extractData)
    {
        var enumValue = EmitValue(extractData.EnumValue);
        var resultName = SanitizeVariableName(extractData.ResultName);
        var enumType = extractData.EnumValue.Type as IrEnumType;

        if (enumType == null)
            throw new InvalidOperationException("ExtractVariantData must be on an enum type");

        var dataType = GetCType(extractData.DataType);

        // Extract data from the specific variant
        _output.AppendLine($"    {dataType} {resultName} = {enumValue}.data.{extractData.VariantName}._{extractData.DataIndex};");
    }

    private string EmitValue(IrValue value)
    {
        return value switch
        {
            IrConstant constant => constant.Value.ToString(),
            IrBoolConstant boolConst => boolConst.Value ? "true" : "false",
            IrVariable variable => SanitizeVariableName(variable.Name),
            IrStringLiteral stringLit => $"(uint8_t*){stringLit.Label}",  // Cast string literal to uint8_t*
            IrEnumValue enumValue => EmitEnumValue(enumValue),
            _ => throw new NotSupportedException($"Unsupported value type: {value.GetType().Name}")
        };
    }

    private string EmitEnumValue(IrEnumValue enumValue)
    {
        var enumType = enumValue.Type as IrEnumType;
        if (enumType == null)
            throw new InvalidOperationException("EnumValue must have IrEnumType");

        var enumName = MangleName(enumType.Name);
        var tempName = $"_enum_{enumValue.VariantName}_{_tempCounter++}";

        // Construct the enum value inline (C99 compound literal)
        var result = $"({enumName}){{ .tag = {enumName}_{enumValue.VariantName}";

        if (enumValue.AssociatedValues.Count > 0)
        {
            result += ", .data = { ." + enumValue.VariantName + " = {";
            for (int i = 0; i < enumValue.AssociatedValues.Count; i++)
            {
                var assocValue = EmitValue(enumValue.AssociatedValues[i]);
                result += $" ._{i} = {assocValue}";
                if (i < enumValue.AssociatedValues.Count - 1)
                    result += ",";
            }
            result += " } }";
        }

        result += " }";
        return result;
    }

    private int _tempCounter = 0;

    private string SanitizeVariableName(string name)
    {
        // Convert IR temp variable names (%t0, %t1, etc.) to valid C identifiers (_t0, _t1, etc.)
        if (name.StartsWith("%"))
        {
            return "_" + name.Substring(1);
        }
        return name;
    }

    private string GetBinaryOperator(IrBinaryOp.OpKind operation)
    {
        return operation switch
        {
            IrBinaryOp.OpKind.Add => "+",
            IrBinaryOp.OpKind.Sub => "-",
            IrBinaryOp.OpKind.Mul => "*",
            IrBinaryOp.OpKind.Div => "/",
            IrBinaryOp.OpKind.Mod => "%",
            IrBinaryOp.OpKind.And => "&",
            IrBinaryOp.OpKind.Or => "|",
            IrBinaryOp.OpKind.Xor => "^",
            IrBinaryOp.OpKind.Shl => "<<",
            IrBinaryOp.OpKind.Shr => ">>",
            IrBinaryOp.OpKind.Eq => "==",
            IrBinaryOp.OpKind.Ne => "!=",
            IrBinaryOp.OpKind.Lt => "<",
            IrBinaryOp.OpKind.Le => "<=",
            IrBinaryOp.OpKind.Gt => ">",
            IrBinaryOp.OpKind.Ge => ">=",
            _ => throw new NotSupportedException($"Unsupported binary operation: {operation}")
        };
    }

    private string GetCType(IrType type)
    {
        return type switch
        {
            IrIntType intType => intType.IsSigned
                ? intType.BitWidth switch
                {
                    8 => "int8_t",
                    16 => "int16_t",
                    32 => "int32_t",
                    64 => "int64_t",
                    _ => throw new NotSupportedException($"Unsupported int width: {intType.BitWidth}")
                }
                : intType.BitWidth switch
                {
                    8 => "uint8_t",
                    16 => "uint16_t",
                    32 => "uint32_t",
                    64 => "uint64_t",
                    _ => throw new NotSupportedException($"Unsupported uint width: {intType.BitWidth}")
                },
            IrBoolType => "bool",
            IrVoidType => "void",
            IrPointerType ptrType => $"{GetCType(ptrType.PointeeType)}*",
            IrStringType => "String",
            IrEnumType enumType => MangleName(enumType.Name),  // For now, just use mangled name
            IrStructType structType => MangleName(structType.Name),  // TODO: Generate struct definition
            IrArrayType arrayType => $"{GetCType(arrayType.ElementType)}*",  // Arrays as pointers for now
            IrReferenceType refType => $"{GetCType(refType.PointeeType)}*",  // References as pointers
            IrMutReferenceType mutRefType => $"{GetCType(mutRefType.PointeeType)}*",  // Mut references as pointers
            _ => throw new NotSupportedException($"Unsupported type: {type.GetType().Name}")
        };
    }

    private string GetParameterList(IrFunction function)
    {
        if (function.Parameters.Count == 0)
            return "void";

        var parameters = function.Parameters
            .Select(p => $"{GetCType(p.Type)} {p.Name}")
            .ToList();

        return string.Join(", ", parameters);
    }

    private string MangleName(string name)
    {
        // For now, keep names simple
        // TODO: Handle generic instantiations, modules, etc.
        return name.Replace("::", "_");
    }
}
