using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Novus.IR;
using Novus.SemanticAnalysis;

namespace Novus.Codegen;

/// <summary>
/// Generates AmigaOS shared library boilerplate from @library attributes.
///
/// When a struct has @library attribute, this generates:
/// - ROMTag structure (for exec.library scanning)
/// - Function vector table (negative offsets from library base)
/// - A6 calling convention wrappers (AmigaOS → C calling convention)
/// - Default lifecycle functions (Open/Close/Expunge/Reserved)
///
/// This eliminates the need for manual assembly files.
/// </summary>
public class LibraryGenerator
{
    private readonly IrModule _module;
    private readonly IrStructType? _libraryStruct;
    private readonly AttributeInfo? _libraryAttribute;
    private readonly List<LibraryFunction> _libraryFunctions;
    private readonly string? _projectVersion;
    private readonly int _versionMajor;
    private readonly int _versionMinor;
    private readonly int _versionPatch;

    /// <summary>
    /// Represents a library function with its metadata.
    /// </summary>
    private class LibraryFunction
    {
        public string Name { get; set; } = "";
        public string CName { get; set; } = "";  // Mangled C name
        public IrFunction Function { get; set; } = null!;
        public int VectorOffset { get; set; }
        public bool IsLifecycleFunction { get; set; }
        public bool IsAutoGenerated { get; set; }  // true for compiler-generated functions
    }

    /// <summary>
    /// Defines an auto-generated library function that all libraries get.
    /// Add new standard library functions here - they'll automatically be:
    /// - Added to the function vector table
    /// - Generated in A6 wrappers
    /// - Generated in client call stubs
    /// - Included in FFI bindings
    /// </summary>
    private class AutoGeneratedFunction
    {
        public string Name { get; set; } = "";
        public string ReturnTypeName { get; set; } = "";  // "LibraryVersion", "u32", etc.
        public bool ReturnsStruct { get; set; }

        public AutoGeneratedFunction(string name, string returnType, bool returnsStruct = false)
        {
            Name = name;
            ReturnTypeName = returnType;
            ReturnsStruct = returnsStruct;
        }
    }

    /// <summary>
    /// Registry of all auto-generated functions that every library gets.
    /// TO ADD A NEW STANDARD FUNCTION: Just add it to this list!
    /// </summary>
    private static readonly AutoGeneratedFunction[] AutoGeneratedFunctions = new[]
    {
        new AutoGeneratedFunction("GetLibraryVersion", "LibraryVersion", returnsStruct: true),
        new AutoGeneratedFunction("GetCallCount", "u32", returnsStruct: false),
        // Add more standard functions here as needed:
        // new AutoGeneratedFunction("GetDebugInfo", "DebugInfo", returnsStruct: true),
    };

    public LibraryGenerator(IrModule module, string? projectVersion = null)
    {
        _module = module;
        _libraryFunctions = new List<LibraryFunction>();
        _projectVersion = projectVersion;

        // Parse semver version (e.g., "1.0.0" -> major=1, minor=0, patch=0)
        if (!string.IsNullOrEmpty(projectVersion))
        {
            var parts = projectVersion.Split('.');
            _versionMajor = parts.Length > 0 && int.TryParse(parts[0], out var major) ? major : 1;
            _versionMinor = parts.Length > 1 && int.TryParse(parts[1], out var minor) ? minor : 0;
            _versionPatch = parts.Length > 2 && int.TryParse(parts[2], out var patch) ? patch : 0;
        }
        else
        {
            // Default to 1.0.0 if no version specified
            _versionMajor = 1;
            _versionMinor = 0;
            _versionPatch = 0;
        }

        // Find the struct with @library attribute
        foreach (var structType in module.Structs)
        {
            if (structType.Attributes?.Has(KnownAttributes.Library) == true)
            {
                _libraryStruct = structType;
                _libraryAttribute = structType.Attributes.Get(KnownAttributes.Library);
                break;
            }
        }

        if (_libraryStruct != null)
        {
            AnalyzeLibraryFunctions();
        }
    }

    /// <summary>
    /// Returns true if this module is a library (has @library attribute).
    /// </summary>
    public bool IsLibrary => _libraryStruct != null;

    /// <summary>
    /// Get the library name from the @library attribute.
    /// </summary>
    public string GetLibraryName()
    {
        if (_libraryAttribute == null)
            return "";

        var name = _libraryAttribute.GetString("name");
        if (name == null)
            throw new InvalidOperationException("@library attribute requires 'name' parameter");

        if (!name.EndsWith(".library"))
            throw new InvalidOperationException("Library name must end with '.library'");

        return name;
    }

    /// <summary>
    /// Get the library version from the @library attribute.
    /// </summary>
    /// <summary>
    /// Get the library major version (from project.toml version field).
    /// </summary>
    public int GetLibraryVersion()
    {
        return _versionMajor;
    }

    /// <summary>
    /// Get the library minor version / revision (from project.toml version field).
    /// </summary>
    public int GetLibraryRevision()
    {
        return _versionMinor;
    }

    /// <summary>
    /// Get the library patch version (from project.toml version field).
    /// </summary>
    public int GetLibraryPatch()
    {
        return _versionPatch;
    }

    /// <summary>
    /// Mangle a Novus name to a C-compatible name (same as CCodeGenerator).
    /// </summary>
    private string MangleName(string name)
    {
        return name.Replace("::", "_");
    }

    /// <summary>
    /// Analyze which functions belong to the library.
    /// </summary>
    private void AnalyzeLibraryFunctions()
    {
        if (_libraryStruct == null)
            return;

        // Find all public functions in impl block for the library struct
        var structName = _libraryStruct.StructName;

        // Vector offset -6: Open
        // Vector offset -12: Close
        // Vector offset -18: Expunge
        // Vector offset -24: Reserved
        // Vector offset -30: First user function
        // Vector offset -36: Second user function
        // etc.

        int nextOffset = -30; // User functions start at -30

        foreach (var function in _module.Functions)
        {
            // Skip extern functions
            if (function.IsExtern)
                continue;

            // Check if this function belongs to the library struct
            // Convention: functions are named "StructName_methodName" or just "methodName"
            // For now, include all public functions (we'll refine this)
            if (!function.IsPublic)
                continue;

            var libFunc = new LibraryFunction
            {
                Name = function.Name,
                CName = MangleName(function.Name),
                Function = function
            };

            // Check if it's a lifecycle function by exact name match
            // Standard AmigaOS lifecycle functions: Open, Close, Expunge, Reserved
            var funcName = function.Name;
            if (funcName == "Open" || funcName == $"{_libraryStruct.StructName}::Open")
            {
                libFunc.VectorOffset = -6;
                libFunc.IsLifecycleFunction = true;
            }
            else if (funcName == "Close" || funcName == $"{_libraryStruct.StructName}::Close")
            {
                libFunc.VectorOffset = -12;
                libFunc.IsLifecycleFunction = true;
            }
            else if (funcName == "Expunge" || funcName == $"{_libraryStruct.StructName}::Expunge")
            {
                libFunc.VectorOffset = -18;
                libFunc.IsLifecycleFunction = true;
            }
            else if (funcName == "Reserved" || funcName == $"{_libraryStruct.StructName}::Reserved")
            {
                libFunc.VectorOffset = -24;
                libFunc.IsLifecycleFunction = true;
            }
            else
            {
                // User function - assign next offset
                libFunc.VectorOffset = nextOffset;
                libFunc.IsLifecycleFunction = false;
                nextOffset -= 6; // Next function
            }

            _libraryFunctions.Add(libFunc);
        }

        // Sort by vector offset (DESCENDING - least negative first)
        // This ensures the first function gets offset -30, second gets -36, etc.
        _libraryFunctions.Sort((a, b) => b.VectorOffset.CompareTo(a.VectorOffset));
    }

    /// <summary>
    /// Generate the ROMTag structure in C.
    /// </summary>
    public string GenerateROMTag()
    {
        if (!IsLibrary)
            return "";

        var sb = new StringBuilder();
        var libName = GetLibraryName();
        var version = GetLibraryVersion();
        var revision = GetLibraryRevision();

        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Library Entry Point");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Libraries need a _start() function that returns -1 to discourage");
        sb.AppendLine("// running from the shell. The real entry is the ROMTag structure.");
        sb.AppendLine();
        sb.AppendLine("LONG _start(void) {");
        sb.AppendLine("    return -1;  // Cannot run from CLI");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// ROMTag (Resident Structure)");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// The ROMTag is scanned by exec.library when the library loads.");
        sb.AppendLine("// It identifies this file as an AmigaOS library and provides");
        sb.AppendLine("// initialization information.");
        sb.AppendLine();

        // Include resident header (libraries.h already included in library base struct)
        sb.AppendLine("#include <exec/resident.h>");
        sb.AppendLine();

        // Library name and ID string
        sb.AppendLine($"static const char LibName[] = \"{libName}\";");
        sb.AppendLine($"static const char LibIdString[] = \"{libName} {version}.{revision}\";");
        sb.AppendLine();

        // Forward declarations
        var structName = $"{_libraryStruct.StructName}Base";
        sb.AppendLine("// Forward declarations for C functions");
        sb.AppendLine("struct InitData {");
        sb.AppendLine("    ULONG LibSize;");
        sb.AppendLine("    APTR  FuncTable;");
        sb.AppendLine("    APTR  DataTable;");
        sb.AppendLine("    APTR  InitFunc;");
        sb.AppendLine("};");
        sb.AppendLine($"struct Library* LibInit(__reg(\"d0\") struct {structName}* base, __reg(\"a0\") BPTR segList, __reg(\"a6\") struct ExecBase* sysBase);");
        sb.AppendLine($"struct Library* LibOpen(struct {structName}* base);");
        sb.AppendLine($"BPTR LibClose(struct {structName}* base);");
        sb.AppendLine($"BPTR LibExpunge(struct {structName}* base);");
        sb.AppendLine("LONG LibReserved(void);");
        sb.AppendLine();

        // Forward declarations for A6 wrapper functions (defined in assembly)
        sb.AppendLine("// Forward declarations for A6 wrapper functions (in assembly)");
        sb.AppendLine("extern void LibOpen_Wrapper(void);");
        sb.AppendLine("extern void LibClose_Wrapper(void);");
        sb.AppendLine("extern void LibExpunge_Wrapper(void);");
        sb.AppendLine("extern void LibReserved_Wrapper(void);");
        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                sb.AppendLine($"extern void {func.CName}_Wrapper(void);");
            }
        }
        // Add auto-generated function wrapper forward declarations (from registry)
        foreach (var autoFunc in AutoGeneratedFunctions)
        {
            sb.AppendLine($"extern void {_libraryStruct.StructName}_{autoFunc.Name}_Wrapper(void);");
        }
        sb.AppendLine();

        // Function table - use wrapper functions for AmigaOS calling convention
        sb.AppendLine("// Function vector table (uses A6 wrappers, non-const for relocations)");
        sb.AppendLine("static APTR FuncTable[] = {");
        sb.AppendLine("    (APTR)LibOpen_Wrapper,");
        sb.AppendLine("    (APTR)LibClose_Wrapper,");
        sb.AppendLine("    (APTR)LibExpunge_Wrapper,");
        sb.AppendLine("    (APTR)LibReserved_Wrapper,");

        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                sb.AppendLine($"    (APTR){func.CName}_Wrapper,  // Offset {func.VectorOffset}");
            }
        }

        // Add auto-generated functions to vector table (from registry)
        var nextOffset = _libraryFunctions.Count(f => !f.IsLifecycleFunction) * 6 + 30;
        foreach (var autoFunc in AutoGeneratedFunctions)
        {
            var funcName = $"{_libraryStruct.StructName}_{autoFunc.Name}";
            sb.AppendLine($"    (APTR){funcName}_Wrapper,  // Offset -{nextOffset} (auto-generated: {autoFunc.Name})");
            nextOffset += 6;
        }

        sb.AppendLine("    (APTR)-1");
        sb.AppendLine("};");
        sb.AppendLine();

        // AutoInit structure - MUST be defined BEFORE RomTag since RomTag references it
        sb.AppendLine("// AutoInit structure (no forward declaration needed)");
        sb.AppendLine("static struct InitData InitTable = {");
        sb.AppendLine($"    sizeof(struct {structName}),  // Data size");
        sb.AppendLine("    (APTR)FuncTable,         // Function table");
        sb.AppendLine("    NULL,                    // Data table");
        sb.AppendLine("    (APTR)LibInit            // Init routine");
        sb.AppendLine("};");
        sb.AppendLine();

        // ROMTag structure
        sb.AppendLine("// ROMTag structure (non-const so relocations are applied correctly)");
        sb.AppendLine("// VBCC automatically aligns struct Resident to LONG (4-byte) boundary");
        sb.AppendLine("struct Resident RomTag = {");
        sb.AppendLine("    RTC_MATCHWORD,       // Magic word");
        sb.AppendLine("    &RomTag,             // Pointer to itself");
        sb.AppendLine("    (APTR)((UBYTE*)&RomTag + sizeof(struct Resident)),  // End marker");
        sb.AppendLine("    RTF_AUTOINIT,        // Flags");
        sb.AppendLine($"    {version},                 // Version");
        sb.AppendLine("    NT_LIBRARY,          // Type");
        sb.AppendLine("    0,                   // Priority");
        sb.AppendLine("    (char*)LibName,      // Name");
        sb.AppendLine("    (char*)LibIdString,  // ID string");
        sb.AppendLine("    (APTR)&InitTable     // Init table pointer");
        sb.AppendLine("};");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Calculate the size of the library base structure.
    /// </summary>
    private int CalculateLibraryBaseSize()
    {
        if (_libraryStruct == null)
            return 0;

        // sizeof(Library) + custom fields
        // Library header is typically 34 bytes on 68k
        int size = 34;

        foreach (var field in _libraryStruct.Fields)
        {
            size += GetFieldSize(field.Type);
        }

        return size;
    }

    /// <summary>
    /// Get the size of a field type in bytes.
    /// </summary>
    private int GetFieldSize(IrType type)
    {
        return type switch
        {
            IrIntType intType => intType.SizeInBytes,
            IrPointerType => 4, // 32-bit pointers on 68k
            IrBoolType => 1,
            _ => throw new InvalidOperationException($"Cannot determine field size for unsupported IR type: {type.GetType().Name}")
        };
    }

    /// <summary>
    /// Get the C type name for an IR type (simplified version from CCodeGenerator).
    /// </summary>
    private string GetCType(IrType type)
    {
        return type switch
        {
            IrIntType intType => intType.IsSigned
                ? $"int{intType.SizeInBytes * 8}_t"
                : $"uint{intType.SizeInBytes * 8}_t",
            IrBoolType => "bool",
            IrPointerType ptrType => $"{GetCType(ptrType.PointeeType)}*",
            _ => throw new InvalidOperationException($"Cannot generate C type for unsupported IR type: {type.GetType().Name}")
        };
    }

    /// <summary>
    /// Generate the library base structure definition.
    /// Includes necessary headers for struct Library definition.
    /// </summary>
    public string GenerateLibraryBaseStruct()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var libName = GetLibraryName();
        var structName = $"{_libraryStruct.StructName}Base";

        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Library Base Structure");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine();

        // Include headers needed for struct Library
        sb.AppendLine("#include <exec/types.h>");
        sb.AppendLine("#include <exec/nodes.h>");
        sb.AppendLine("#include <exec/libraries.h>");
        sb.AppendLine("#include <dos/dos.h>");  // For BPTR
        sb.AppendLine();

        // Include proto files for Exec functions (VBCC inlines)
        sb.AppendLine("// Exec library proto for inline functions");
        sb.AppendLine("#include <proto/exec.h>");
        sb.AppendLine();

        sb.AppendLine($"// The library base includes the standard Library header plus custom fields.");
        sb.AppendLine($"struct {structName} {{");
        sb.AppendLine("    struct Library lib;");
        sb.AppendLine("    BPTR lib_SegList;  // Segment list for library unloading");
        sb.AppendLine("    UWORD lib_Patch;   // Patch version for full semver support (major.minor.patch)");
        sb.AppendLine("    ULONG __call_count;  // Auto-generated: total library function calls");

        // Add custom fields from the @library struct (skip call_count if user defined it)
        foreach (var field in _libraryStruct.Fields)
        {
            if (field.Name == "call_count")
                continue;  // Skip - we provide it automatically as __call_count

            var cType = GetCType(field.Type);
            sb.AppendLine($"    {cType} {field.Name};");
        }

        sb.AppendLine("};");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate default lifecycle functions if not provided by user.
    /// </summary>
    public string GenerateDefaultLifecycleFunctions()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var structName = $"{_libraryStruct.StructName}Base";

        // Check which lifecycle functions are missing
        bool hasOpen = _libraryFunctions.Any(f => f.VectorOffset == -6);
        bool hasClose = _libraryFunctions.Any(f => f.VectorOffset == -12);
        bool hasExpunge = _libraryFunctions.Any(f => f.VectorOffset == -18);
        bool hasReserved = _libraryFunctions.Any(f => f.VectorOffset == -24);

        // Use extern SysBase from runtime, or get it from location 4
        sb.AppendLine("// Get exec.library base from absolute location 4");
        sb.AppendLine("#define SysBase (*(struct ExecBase**)4)");
        sb.AppendLine();

        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Lifecycle Functions");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine();

        // LibInit - always generate this as it's required
        // AutoInit calls with: D0=base, A0=segList, A6=SysBase
        sb.AppendLine($"struct Library* LibInit(__reg(\"d0\") struct {structName}* base, __reg(\"a0\") BPTR segList, __reg(\"a6\") struct ExecBase* sysBase) {{");
        sb.AppendLine("    // Initialize library base fields");
        sb.AppendLine("    // Node fields (ln_Succ and ln_Pred set by Exec's AddLibrary)");
        sb.AppendLine("    base->lib.lib_Node.ln_Type = NT_LIBRARY;");
        sb.AppendLine("    base->lib.lib_Node.ln_Pri = 0;");
        sb.AppendLine("    base->lib.lib_Node.ln_Name = (char*)LibName;");
        sb.AppendLine("    // Library fields (NegSize/PosSize set by MakeLibrary)");
        sb.AppendLine("    base->lib.lib_Flags = LIBF_CHANGED;  // Don't use SUMUSED without initializing lib_Sum");
        sb.AppendLine("    base->lib.lib_OpenCnt = 0;  // Initialize to zero");
        sb.AppendLine($"    base->lib.lib_Version = {GetLibraryVersion()};");
        sb.AppendLine($"    base->lib.lib_Revision = {GetLibraryRevision()};");
        sb.AppendLine("    base->lib.lib_IdString = (char*)LibIdString;");
        sb.AppendLine();
        sb.AppendLine("    // Store segment list and version info");
        sb.AppendLine("    base->lib_SegList = segList;");
        sb.AppendLine($"    base->lib_Patch = {GetLibraryPatch()};  // Semver patch version");
        sb.AppendLine();

        // Initialize auto-generated call counter
        sb.AppendLine("    // Initialize auto-generated call counter");
        sb.AppendLine("    base->__call_count = 0;");
        sb.AppendLine();

        // Initialize custom fields from @library struct (skip call_count if user defined it)
        if (_libraryStruct.Fields.Count > 0)
        {
            sb.AppendLine("    // Initialize custom library fields");
            foreach (var field in _libraryStruct.Fields)
            {
                if (field.Name == "call_count")
                    continue;  // Skip - we use __call_count instead

                sb.AppendLine($"    base->{field.Name} = 0;  // Initialize to zero");
            }
            sb.AppendLine();
        }

        sb.AppendLine("    return &base->lib;");
        sb.AppendLine("}");
        sb.AppendLine();

        if (!hasOpen)
        {
            sb.AppendLine($"struct Library* LibOpen(struct {structName}* base) {{");
            sb.AppendLine("    base->lib.lib_OpenCnt++;");
            sb.AppendLine("    base->lib.lib_Flags &= ~LIBF_DELEXP;");
            sb.AppendLine("    return &base->lib;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (!hasClose)
        {
            sb.AppendLine($"BPTR LibClose(struct {structName}* base) {{");
            sb.AppendLine("    base->lib.lib_OpenCnt--;");
            sb.AppendLine("    if (base->lib.lib_OpenCnt == 0 && (base->lib.lib_Flags & LIBF_DELEXP)) {");
            sb.AppendLine("        return LibExpunge(base);");
            sb.AppendLine("    }");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (!hasExpunge)
        {
            sb.AppendLine($"BPTR LibExpunge(struct {structName}* base) {{");
            sb.AppendLine("    if (base->lib.lib_OpenCnt > 0) {");
            sb.AppendLine("        base->lib.lib_Flags |= LIBF_DELEXP;");
            sb.AppendLine("        return 0;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    // Save segList before freeing base");
            sb.AppendLine("    BPTR segList = base->lib_SegList;");
            sb.AppendLine();
            sb.AppendLine("    // Remove library from system list");
            sb.AppendLine("    Remove((struct Node*)&base->lib);");
            sb.AppendLine();
            sb.AppendLine("    // Calculate total memory size (including negative space for function vectors)");
            sb.AppendLine("    ULONG memSize = base->lib.lib_NegSize + base->lib.lib_PosSize;");
            sb.AppendLine("    void* memStart = (void*)((UBYTE*)base - base->lib.lib_NegSize);");
            sb.AppendLine();
            sb.AppendLine("    // Free library base memory");
            sb.AppendLine("    FreeMem(memStart, memSize);");
            sb.AppendLine();
            sb.AppendLine("    // Return segment list for DOS to unload");
            sb.AppendLine("    return segList;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (!hasReserved)
        {
            sb.AppendLine("LONG LibReserved(void) {");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Auto-generate GetLibraryVersion function for all libraries
        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Auto-Generated Version Function");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine();
        sb.AppendLine("// LibraryVersion struct (matches std::core::LibraryVersion)");
        sb.AppendLine("struct LibraryVersion {");
        sb.AppendLine("    uint16_t major;");
        sb.AppendLine("    uint16_t minor;");
        sb.AppendLine("    uint16_t patch;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine($"// Auto-generated function to get library version from {structName}");
        sb.AppendLine($"// Uses pointer parameter to avoid VBCC struct return hidden pointer issues");
        sb.AppendLine($"void {_libraryStruct.StructName}_GetLibraryVersion(struct {structName}* base, struct LibraryVersion* result) {{");
        sb.AppendLine("    result->major = base->lib.lib_Version;");
        sb.AppendLine("    result->minor = base->lib.lib_Revision;");
        sb.AppendLine("    result->patch = base->lib_Patch;");
        sb.AppendLine("}");
        sb.AppendLine();

        // Auto-generate GetCallCount function
        sb.AppendLine("// ============================================================================");
        sb.AppendLine("// Auto-Generated Call Counter Functions");
        sb.AppendLine("// ============================================================================");
        sb.AppendLine();
        sb.AppendLine($"// Internal function to increment call counter");
        sb.AppendLine($"void {_libraryStruct.StructName}_IncrementCallCount(struct {structName}* base) {{");
        sb.AppendLine("    if (base != NULL) {");
        sb.AppendLine("        base->__call_count++;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"// Auto-generated function to get total library function calls");
        sb.AppendLine($"uint32_t {_libraryStruct.StructName}_GetCallCount(struct {structName}* base) {{");
        sb.AppendLine("    if (base == NULL) return 0;");
        sb.AppendLine("    return base->__call_count;");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate A6 wrapper assembly for AmigaOS calling convention.
    /// These wrappers translate from register-based (A6=LibBase) to C calling convention.
    /// </summary>
    public string GenerateA6Wrappers()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var structName = $"{_libraryStruct.StructName}Base";

        sb.AppendLine("; A6 Wrapper Functions for AmigaOS Calling Convention");
        sb.AppendLine("; Generated by Novus compiler");
        sb.AppendLine(";");
        sb.AppendLine("; AmigaOS calls library functions with:");
        sb.AppendLine(";   A6 = Library base pointer");
        sb.AppendLine(";   Parameters in D0/D1/A0/A1/D2/D3/A2/A3...");
        sb.AppendLine(";");
        sb.AppendLine("; These wrappers translate to C convention:");
        sb.AppendLine(";   Parameters pushed on stack (right to left)");
        sb.AppendLine(";   A6 passed as first parameter");
        sb.AppendLine(";   Result returned in D0");
        sb.AppendLine();

        sb.AppendLine("        SECTION CODE");
        sb.AppendLine();

        // Generate wrappers for lifecycle functions
        sb.AppendLine("; Lifecycle Function Wrappers");
        sb.AppendLine();

        // LibOpen wrapper: receives A6=base, calls LibOpen(base)
        sb.AppendLine("        XDEF    _LibOpen_Wrapper");
        sb.AppendLine("        XREF    _LibOpen");
        sb.AppendLine("_LibOpen_Wrapper:");
        sb.AppendLine("        move.l  a6,-(sp)        ; Push library base as parameter");
        sb.AppendLine("        jsr     _LibOpen        ; Call C function");
        sb.AppendLine("        addq.l  #4,sp           ; Clean up stack");
        sb.AppendLine("        rts                     ; Return (result in D0)");
        sb.AppendLine();

        // LibClose wrapper: receives A6=base, calls LibClose(base)
        sb.AppendLine("        XDEF    _LibClose_Wrapper");
        sb.AppendLine("        XREF    _LibClose");
        sb.AppendLine("_LibClose_Wrapper:");
        sb.AppendLine("        move.l  a6,-(sp)        ; Push library base");
        sb.AppendLine("        jsr     _LibClose       ; Call C function");
        sb.AppendLine("        addq.l  #4,sp           ; Clean up stack");
        sb.AppendLine("        rts");
        sb.AppendLine();

        // LibExpunge wrapper: receives A6=base, calls LibExpunge(base)
        sb.AppendLine("        XDEF    _LibExpunge_Wrapper");
        sb.AppendLine("        XREF    _LibExpunge");
        sb.AppendLine("_LibExpunge_Wrapper:");
        sb.AppendLine("        move.l  a6,-(sp)        ; Push library base");
        sb.AppendLine("        jsr     _LibExpunge     ; Call C function");
        sb.AppendLine("        addq.l  #4,sp           ; Clean up stack");
        sb.AppendLine("        rts");
        sb.AppendLine();

        // LibReserved wrapper
        sb.AppendLine("        XDEF    _LibReserved_Wrapper");
        sb.AppendLine("        XREF    _LibReserved");
        sb.AppendLine("_LibReserved_Wrapper:");
        sb.AppendLine("        jsr     _LibReserved    ; No parameters");
        sb.AppendLine("        rts");
        sb.AppendLine();

        // Generate wrappers for user functions
        sb.AppendLine("; User Function Wrappers");
        sb.AppendLine();

        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                GenerateUserFunctionWrapper(sb, func);
            }
        }

        // Generate wrapper for auto-generated GetLibraryVersion function
        sb.AppendLine("; Auto-Generated Function Wrappers");
        sb.AppendLine("; NOTE: These wrappers do NOT increment __call_count (introspection functions)");
        sb.AppendLine();
        var getVersionName = $"{_libraryStruct.StructName}_GetLibraryVersion";
        sb.AppendLine($"; Wrapper for {getVersionName}");
        sb.AppendLine($"; Note: Caller passes result pointer in A0, library base in A6");
        sb.AppendLine($"        XDEF    _{getVersionName}_Wrapper");
        sb.AppendLine($"        XREF    _{getVersionName}");
        sb.AppendLine($"_{getVersionName}_Wrapper:");
        sb.AppendLine("        move.l  a0,-(sp)        ; Push result pointer (will be 2nd param after JSR)");
        sb.AppendLine("        move.l  a6,-(sp)        ; Push library base (will be 1st param after JSR)");
        sb.AppendLine($"        jsr     _{getVersionName} ; Call C function");
        sb.AppendLine("        addq.l  #8,sp           ; Clean up parameters (base + result pointer)");
        sb.AppendLine("        rts                     ; No return value (result written via pointer)");
        sb.AppendLine();

        // Generate wrapper for auto-generated GetCallCount function
        var getCallCountName = $"{_libraryStruct.StructName}_GetCallCount";
        sb.AppendLine($"; Wrapper for {getCallCountName}");
        sb.AppendLine($"; Returns call count in D0, library base passed in A6");
        sb.AppendLine($"        XDEF    _{getCallCountName}_Wrapper");
        sb.AppendLine($"        XREF    _{getCallCountName}");
        sb.AppendLine($"_{getCallCountName}_Wrapper:");
        sb.AppendLine("        move.l  a6,-(sp)        ; Push library base as parameter");
        sb.AppendLine($"        jsr     _{getCallCountName} ; Call C function (returns count in D0)");
        sb.AppendLine("        addq.l  #4,sp           ; Clean up parameter");
        sb.AppendLine("        rts                     ; Return with count in D0");
        sb.AppendLine();

        sb.AppendLine("        END");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate A6 wrapper for a user library function.
    /// </summary>
    private void GenerateUserFunctionWrapper(StringBuilder sb, LibraryFunction func)
    {
        var wrapperName = $"_{func.CName}_Wrapper";
        var cFuncName = $"_{func.CName}";

        sb.AppendLine($"; Wrapper for {func.CName}");
        sb.AppendLine($"        XDEF    {wrapperName}");
        sb.AppendLine($"        XREF    {cFuncName}");
        sb.AppendLine($"        XREF    _{_libraryStruct.StructName}_IncrementCallCount");
        sb.AppendLine($"{wrapperName}:");

        // Auto-increment call counter by calling C helper function
        // This ensures VBCC calculates the correct offset for __call_count
        // instead of hardcoding it in assembly (which can be wrong due to padding)
        sb.AppendLine("        movem.l d0-d1/a0-a1,-(sp)  ; Save registers");
        sb.AppendLine("        move.l  a6,-(sp)            ; Push library base");
        sb.AppendLine($"        jsr     _{_libraryStruct.StructName}_IncrementCallCount");
        sb.AppendLine("        addq.l  #4,sp               ; Clean up parameter");
        sb.AppendLine("        movem.l (sp)+,d0-d1/a0-a1  ; Restore registers");

        // For now, generate a simple wrapper that just calls the function
        // TODO: Need to analyze function signature to properly marshal parameters
        var parameters = func.Function.Parameters;

        if (parameters.Count == 0)
        {
            // No parameters - just call the function directly
            sb.AppendLine($"        jsr     {cFuncName}");
        }
        else
        {
            // Push parameters in reverse order (right to left for C convention)
            // User parameters come in D0, D1, A0, A1 order

            for (int i = parameters.Count - 1; i >= 0; i--)
            {
                var param = parameters[i];
                if (i == 0)
                {
                    // First parameter - D0 or A0 depending on type
                    if (IsPointerType(param.Type))
                        sb.AppendLine("        move.l  a0,-(sp)");
                    else
                        sb.AppendLine("        move.l  d0,-(sp)");
                }
                else if (i == 1)
                {
                    // Second parameter - D1 or A1
                    if (IsPointerType(param.Type))
                        sb.AppendLine("        move.l  a1,-(sp)");
                    else
                        sb.AppendLine("        move.l  d1,-(sp)");
                }
                // TODO: Handle more parameters (D2, D3, A2, A3...)
            }

            sb.AppendLine($"        jsr     {cFuncName}");

            // Clean up stack (4 bytes per parameter)
            int stackCleanup = parameters.Count * 4;
            if (stackCleanup <= 8)
                sb.AppendLine($"        addq.l  #{stackCleanup},sp");
            else
                sb.AppendLine($"        add.l   #{stackCleanup},sp");
        }

        sb.AppendLine("        rts");
        sb.AppendLine();
    }

    /// <summary>
    /// Check if a type is a pointer type.
    /// </summary>
    private bool IsPointerType(IrType type)
    {
        return type is IrPointerType;
    }

    /// <summary>
    /// Generate C header file for the library.
    /// This allows C programs to use the library.
    /// </summary>
    public string GenerateCHeader()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var libName = GetLibraryName();
        var structName = $"{_libraryStruct.StructName}Base";
        var headerGuard = $"_{libName.Replace(".", "_").ToUpper()}_H";

        sb.AppendLine($"#ifndef {headerGuard}");
        sb.AppendLine($"#define {headerGuard}");
        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine($" * {libName} - C Interface");
        sb.AppendLine($" * Generated by Novus compiler");
        sb.AppendLine($" * Version: {GetLibraryVersion()}.{GetLibraryRevision()}");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine("#include <exec/types.h>");
        sb.AppendLine("#include <exec/libraries.h>");
        sb.AppendLine();

        // Library base structure
        sb.AppendLine("/* Library base structure */");
        sb.AppendLine($"struct {structName} {{");
        sb.AppendLine("    struct Library lib;");

        // Always add call_count field for automatic tracking (reserved field)
        sb.AppendLine("    ULONG __call_count;  /* Auto-generated: total library function calls */");

        // Add custom fields (skip call_count if user defined it - we use __call_count instead)
        foreach (var field in _libraryStruct.Fields)
        {
            if (field.Name == "call_count")
                continue;  // Skip user-defined call_count - we provide it automatically

            var cType = GetCType(field.Type);
            sb.AppendLine($"    {cType} {field.Name};");
        }
        sb.AppendLine("};");
        sb.AppendLine();

        // Library base pointer (auto-opened by linker stub)
        sb.AppendLine($"/* Library base pointer (auto-opened at program startup) */");
        sb.AppendLine($"extern struct {structName}* _{_libraryStruct.StructName}Base;");
        sb.AppendLine($"#define {_libraryStruct.StructName}Base _{_libraryStruct.StructName}Base");
        sb.AppendLine();

        // Function prototypes (using library base in A6)
        sb.AppendLine("/* Library functions */");
        sb.AppendLine("#ifdef __VBCC__");
        sb.AppendLine("/* VBCC inline calling convention */");

        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                var returnType = GetCType(func.Function.ReturnType);
                var paramList = string.Join(", ", func.Function.Parameters.Select(p =>
                    $"{GetCType(p.Type)} {p.Name}"));

                if (string.IsNullOrEmpty(paramList))
                    paramList = "void";

                var offset = Math.Abs(func.VectorOffset);
                sb.AppendLine($"{returnType} {func.CName}({paramList})");
                sb.AppendLine($"    = \"\\tjsr\\t-{offset}(a6)\";");
            }
        }

        sb.AppendLine("#else");
        sb.AppendLine("/* Standard C prototypes */");
        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                var returnType = GetCType(func.Function.ReturnType);
                var paramList = string.Join(", ", func.Function.Parameters.Select(p =>
                    $"{GetCType(p.Type)} {p.Name}"));

                if (string.IsNullOrEmpty(paramList))
                    paramList = "void";

                sb.AppendLine($"{returnType} {func.CName}({paramList});");
            }
        }
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine($"#endif /* {headerGuard} */");

        return sb.ToString();
    }

    /// <summary>
    /// Generate Novus FFI binding for the library.
    /// This allows Novus programs to import and use the library.
    /// </summary>
    public string GenerateNovusFFI()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var libName = GetLibraryName();
        var moduleName = _libraryStruct.StructName.ToLower();

        sb.AppendLine("//");
        sb.AppendLine($"// {libName} - Novus FFI Binding");
        sb.AppendLine("// Generated by Novus compiler");
        sb.AppendLine($"// Version: {GetLibraryVersion()}.{GetLibraryRevision()}");
        sb.AppendLine("//");
        sb.AppendLine();
        sb.AppendLine("from std::ffi::exec import Library, OpenLibrary, CloseLibrary");
        sb.AppendLine();

        // Library base type
        sb.AppendLine("// Library base structure");
        sb.AppendLine($"pub struct {_libraryStruct.StructName}Base {{");
        sb.AppendLine("    lib_node: Library,");

        // Add custom fields with Novus types
        foreach (var field in _libraryStruct.Fields)
        {
            var novusType = GetNovusType(field.Type);
            sb.AppendLine($"    {field.Name}: {novusType},");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Library handle
        sb.AppendLine("// Global library base (initialized via open_library)");
        sb.AppendLine($"static mut {_libraryStruct.StructName}_BASE: *{_libraryStruct.StructName}Base = 0 as *{_libraryStruct.StructName}Base;");
        sb.AppendLine();

        // Open library function
        sb.AppendLine("// Open the library");
        sb.AppendLine($"pub fn open_{moduleName}(version: u32) -> bool {{");
        sb.AppendLine($"    unsafe {{");
        sb.AppendLine($"        {_libraryStruct.StructName}_BASE = OpenLibrary(\"{libName}\", version) as *{_libraryStruct.StructName}Base;");
        sb.AppendLine($"        return {_libraryStruct.StructName}_BASE != 0 as *{_libraryStruct.StructName}Base;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Close library function
        sb.AppendLine("// Close the library");
        sb.AppendLine($"pub fn close_{moduleName}() {{");
        sb.AppendLine("    unsafe {");
        sb.AppendLine($"        if {_libraryStruct.StructName}_BASE != 0 as *{_libraryStruct.StructName}Base {{");
        sb.AppendLine($"            CloseLibrary({_libraryStruct.StructName}_BASE as *Library);");
        sb.AppendLine($"            {_libraryStruct.StructName}_BASE = 0 as *{_libraryStruct.StructName}Base;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // FFI function declarations
        sb.AppendLine("// Library functions (FFI declarations)");
        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                var returnType = GetNovusType(func.Function.ReturnType);
                var offset = Math.Abs(func.VectorOffset);
                var cleanName = func.Function.Name.Replace("::", "_");

                sb.AppendLine($"#[link_name = \"@{offset}\"]");
                sb.Append($"extern fn {cleanName}_ffi(base: *{_libraryStruct.StructName}Base");

                foreach (var param in func.Function.Parameters)
                {
                    sb.Append($", {param.Name}: {GetNovusType(param.Type)}");
                }

                sb.AppendLine($") -> {returnType};");
                sb.AppendLine();
            }
        }
        sb.AppendLine();

        // Safe wrapper functions
        sb.AppendLine("// Safe wrapper functions");
        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                var returnType = GetNovusType(func.Function.ReturnType);
                var cleanName = func.Function.Name.Replace("::", "_");

                sb.Append($"pub fn {cleanName}(");

                var paramList = string.Join(", ", func.Function.Parameters.Select(p =>
                    $"{p.Name}: {GetNovusType(p.Type)}"));

                sb.Append(paramList);
                sb.AppendLine($") -> {returnType} {{");
                sb.AppendLine("    unsafe {");

                sb.Append($"        return {cleanName}_ffi({_libraryStruct.StructName}_BASE");

                foreach (var param in func.Function.Parameters)
                {
                    sb.Append($", {param.Name}");
                }

                sb.AppendLine(");");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate FD (Function Description) file for VBCC auto-library support.
    /// This allows VBCC to automatically open/close the library like NDK libraries.
    /// </summary>
    public string GenerateFDFile()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var baseName = $"_{_libraryStruct.StructName}Base";

        sb.AppendLine($"##base {baseName}");
        sb.AppendLine("##bias 30");
        sb.AppendLine("##public");

        // Generate FD entries for each user function
        foreach (var func in _libraryFunctions)
        {
            if (!func.IsLifecycleFunction)
            {
                var funcName = func.CName;
                var parameters = func.Function.Parameters;

                // Build parameter list
                var paramNames = string.Join(",", parameters.Select(p => p.Name));

                // Build register list (d0, d1, a0, a1, etc.)
                var registers = new List<string>();
                for (int i = 0; i < parameters.Count && i < 4; i++)
                {
                    var param = parameters[i];
                    // Use data registers for integers, address registers for pointers
                    if (IsPointerType(param.Type))
                    {
                        registers.Add(i == 0 ? "a0" : i == 1 ? "a1" : "a2");
                    }
                    else
                    {
                        registers.Add(i == 0 ? "d0" : i == 1 ? "d1" : "d2");
                    }
                }

                var registerList = string.Join("/", registers);

                // FD format: FunctionName(param1,param2)(d0/d1)
                if (parameters.Count == 0)
                {
                    sb.AppendLine($"{funcName}()()");
                }
                else
                {
                    sb.AppendLine($"{funcName}({paramNames})({registerList})");
                }
            }
        }

        // Add auto-generated GetLibraryVersion function
        // This function takes a pointer parameter for the result (avoids struct return issues)
        sb.AppendLine($"{_libraryStruct.StructName}_GetLibraryVersion(result)(a0)");

        sb.AppendLine("##end");

        return sb.ToString();
    }

    /// <summary>
    /// Generate library stub assembly for auto-open/close support.
    /// This creates the library base variable and auto-init/cleanup code.
    /// </summary>
    public string GenerateLibraryStub()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var baseName = $"_{_libraryStruct.StructName}Base";
        var libName = GetLibraryName();
        var minVersion = GetLibraryVersion();
        var initName = $"__INIT_{libName.Replace(".", "_")}";
        var exitName = $"__EXIT_{libName.Replace(".", "_")}";

        sb.AppendLine("; Auto-generated library stub for VBCC");
        sb.AppendLine($"; Opens {libName} automatically");
        sb.AppendLine();
        sb.AppendLine("        SECTION __MERGED,DATA");
        sb.AppendLine();
        sb.AppendLine($"; Library base variable (exported for use in programs)");
        sb.AppendLine($"        XDEF    {baseName}");
        sb.AppendLine($"{baseName}:");
        sb.AppendLine("        dc.l    0");
        sb.AppendLine();
        sb.AppendLine("; Library name string");
        sb.AppendLine("LibName:");
        sb.AppendLine($"        dc.b    '{libName}',0");
        sb.AppendLine("        EVEN");
        sb.AppendLine();
        sb.AppendLine("; Constructor (called at program startup)");
        sb.AppendLine("        SECTION CODE");
        sb.AppendLine($"        XDEF    {initName}");
        sb.AppendLine($"{initName}:");
        sb.AppendLine("        movem.l d0-d1/a0-a1/a6,-(sp)");
        sb.AppendLine("        move.l  4.w,a6          ; Get ExecBase");
        sb.AppendLine("        lea     LibName(pc),a1  ; Library name");
        sb.AppendLine($"        moveq   #{minVersion},d0         ; Minimum version");
        sb.AppendLine("        jsr     -552(a6)        ; OpenLibrary");
        sb.AppendLine($"        lea     {baseName}(pc),a0");
        sb.AppendLine("        move.l  d0,(a0)         ; Store library base");
        sb.AppendLine("        movem.l (sp)+,d0-d1/a0-a1/a6");
        sb.AppendLine("        rts");
        sb.AppendLine();
        sb.AppendLine("; Destructor (called at program exit)");
        sb.AppendLine($"        XDEF    {exitName}");
        sb.AppendLine($"{exitName}:");
        sb.AppendLine("        movem.l a1/a6,-(sp)");
        sb.AppendLine($"        move.l  {baseName}(pc),d0");
        sb.AppendLine("        beq.s   .skip");
        sb.AppendLine("        move.l  d0,a1           ; Library base");
        sb.AppendLine("        move.l  4.w,a6          ; Get ExecBase");
        sb.AppendLine("        jsr     -414(a6)        ; CloseLibrary");
        sb.AppendLine(".skip:");
        sb.AppendLine("        movem.l (sp)+,a1/a6");
        sb.AppendLine("        rts");
        sb.AppendLine();
        sb.AppendLine("; Register constructor/destructor with linker sets");
        sb.AppendLine("        SECTION ___CTOR_LIST__,DATA");
        sb.AppendLine($"        dc.l    {initName}");
        sb.AppendLine("        SECTION ___DTOR_LIST__,DATA");
        sb.AppendLine($"        dc.l    {exitName}");
        sb.AppendLine();
        sb.AppendLine("        END");

        return sb.ToString();
    }

    /// <summary>
    /// Generates client-side call stubs for calling the library from Novus programs.
    /// These stubs handle opening the library and calling functions via their vector offsets.
    /// </summary>
    public string GenerateClientCallStubs()
    {
        if (!IsLibrary || _libraryStruct == null)
            return "";

        var sb = new StringBuilder();
        var libName = GetLibraryName();
        var baseName = $"_{_libraryStruct.StructName}Base";

        sb.AppendLine($"; Auto-generated client call stubs for {libName}");
        sb.AppendLine("; These allow Novus programs to call library functions");
        sb.AppendLine();
        sb.AppendLine("        SECTION CODE");
        sb.AppendLine();
        sb.AppendLine("; Open library (called before first use)");
        sb.AppendLine("OpenLib:");
        sb.AppendLine($"        tst.l   {baseName}.l");
        sb.AppendLine("        bne.s   .already_open");
        sb.AppendLine();
        sb.AppendLine("        movem.l d0-d1/a0-a1/a6,-(sp)");
        sb.AppendLine("        move.l  4.w,a6                  ; ExecBase");
        sb.AppendLine("        lea     LibName,a1              ; Library name");
        sb.AppendLine($"        moveq   #{GetLibraryVersion()},d0           ; Min version");
        sb.AppendLine("        jsr     -552(a6)                ; OpenLibrary");
        sb.AppendLine($"        move.l  d0,{baseName}.l         ; Store with absolute addressing");
        sb.AppendLine("        movem.l (sp)+,d0-d1/a0-a1/a6");
        sb.AppendLine(".already_open:");
        sb.AppendLine("        rts");
        sb.AppendLine();

        // Generate call stub for each library function (including GetLibraryVersion)
        // Only skip Open, Close, Expunge, Reserved (true lifecycle functions)
        foreach (var func in _libraryFunctions.Where(f => !f.IsLifecycleFunction))
        {
            // Strip namespace prefix if present (e.g., "GreetingLibrary::Add" -> "Add")
            var funcName = func.Name.Contains("::") ? func.Name.Split("::")[^1] : func.Name;
            var callName = $"_call_{_libraryStruct.StructName}_{funcName}";
            var returnType = func.Function.ReturnType;
            var isStructReturn = returnType is IrStructType;

            sb.AppendLine($"; {func.Name}");
            sb.AppendLine($"        XDEF    {callName}");
            sb.AppendLine($"{callName}:");
            sb.AppendLine("        jsr     OpenLib");
            sb.AppendLine($"        move.l  {baseName}.l,a6      ; Load library base");
            sb.AppendLine("        tst.l   a6                       ; Check if library opened");
            sb.AppendLine("        beq.s   .fail");

            // Handle struct return (VBCC passes hidden result pointer as first param on stack)
            if (isStructReturn)
            {
                sb.AppendLine("        move.l  4(sp),a0                 ; A0 = result pointer passed by VBCC");
            }
            // Load parameters into registers for simple functions
            else if (func.Function.Parameters.Count > 0)
            {
                var stackOffset = 4;
                for (int i = 0; i < func.Function.Parameters.Count && i < 2; i++)
                {
                    var reg = i == 0 ? "d0" : "d1";
                    sb.AppendLine($"        move.l  {stackOffset}(sp),{reg}       ; Parameter {i + 1}");
                    stackOffset += 4;
                }
            }

            sb.AppendLine($"        jsr     {func.VectorOffset}(a6)      ; Call {func.Name}");
            sb.AppendLine("        rts");

            sb.AppendLine(".fail:");
            // Zero out return value on failure
            if (isStructReturn)
            {
                var structType = returnType as IrStructType;
                var structSize = structType?.Fields.Sum(f => GetTypeSize(f.Type)) ?? 0;
                sb.AppendLine("        move.l  4(sp),a0                 ; Get result pointer");
                for (int i = 0; i < structSize; i += 2)
                {
                    if (i == 0)
                        sb.AppendLine("        clr.w   (a0)+");
                    else
                        sb.AppendLine("        clr.w   (a0)+");
                }
            }
            else
            {
                sb.AppendLine("        moveq   #0,d0");
            }
            sb.AppendLine("        rts");
            sb.AppendLine();
        }

        // Add auto-generated function call stubs (from registry)
        var userFunctionCount = _libraryFunctions.Count(f => !f.IsLifecycleFunction);
        var autoGenOffset = -(userFunctionCount * 6 + 30);

        foreach (var autoFunc in AutoGeneratedFunctions)
        {
            sb.AppendLine($"; {autoFunc.Name} (auto-generated)");
            sb.AppendLine($"        XDEF    _call_{_libraryStruct.StructName}_{autoFunc.Name}");
            sb.AppendLine($"_call_{_libraryStruct.StructName}_{autoFunc.Name}:");
            sb.AppendLine("        jsr     OpenLib");
            sb.AppendLine($"        move.l  {baseName}.l,a6      ; Load library base");
            sb.AppendLine("        tst.l   a6                       ; Check if library opened");
            sb.AppendLine("        beq.s   .fail");

            if (autoFunc.ReturnsStruct)
            {
                sb.AppendLine("        move.l  4(sp),a0                 ; A0 = result pointer passed by VBCC");
            }

            sb.AppendLine($"        jsr     {autoGenOffset}(a6)      ; Call {autoFunc.Name}");
            sb.AppendLine("        rts");
            sb.AppendLine(".fail:");

            if (autoFunc.ReturnsStruct)
            {
                // Zero out struct return - for LibraryVersion this is 6 bytes (3 u16s)
                sb.AppendLine("        move.l  4(sp),a0                 ; Get result pointer");
                sb.AppendLine("        clr.w   (a0)+                    ; Zero field 1");
                sb.AppendLine("        clr.w   (a0)+                    ; Zero field 2");
                sb.AppendLine("        clr.w   (a0)+                    ; Zero field 3");
            }
            else
            {
                sb.AppendLine("        moveq   #0,d0                    ; Return 0 on failure");
            }

            sb.AppendLine("        rts");
            sb.AppendLine();

            autoGenOffset -= 6;  // Next function offset
        }

        // Data section
        sb.AppendLine("        SECTION DATA");
        sb.AppendLine();
        sb.AppendLine("        EVEN");
        sb.AppendLine($"{baseName}:");
        sb.AppendLine("        dc.l    0");
        sb.AppendLine();
        sb.AppendLine("LibName:");
        sb.AppendLine($"        dc.b    '{libName}',0");
        sb.AppendLine("        EVEN");
        sb.AppendLine();
        sb.AppendLine("        END");

        return sb.ToString();
    }

    /// <summary>
    /// Get the size of a type in bytes.
    /// </summary>
    private int GetTypeSize(IrType type)
    {
        return type switch
        {
            IrIntType it => it.BitWidth / 8,
            IrBoolType => 1,
            IrPointerType => 4,
            IrStructType st => st.Fields.Sum(f => GetTypeSize(f.Type)),
            _ => 4
        };
    }

    /// <summary>
    /// Convert IR type to Novus type string.
    /// </summary>
    private string GetNovusType(IrType type)
    {
        return type switch
        {
            IrIntType intType => intType.IsSigned
                ? intType.BitWidth switch
                {
                    8 => "i8",
                    16 => "i16",
                    32 => "i32",
                    64 => "i64",
                    _ => "i32"
                }
                : intType.BitWidth switch
                {
                    8 => "u8",
                    16 => "u16",
                    32 => "u32",
                    64 => "u64",
                    _ => "u32"
                },
            IrBoolType => "bool",
            IrVoidType => "()",
            IrPointerType pt => $"*{GetNovusType(pt.PointeeType)}",
            IrStructType st => st.Name,
            _ => "i32"
        };
    }
}
